### ISSUE TITLE
Batman: Return of the Joker - Crashes on game start

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/NES_MiSTer#108]
This happens with both the Japanese version titled Dynamite Batman, and the US Batman: Return of the Joker. The title screen is fine, but when you start a new game, after the "Stage 1-1" screen, the game will freeze.

Appears to use mapper 69 like Gimmick, but the FME-7 variant with no expansion sound.

http://bootgod.dyndns.org:7777/profile.php?id=657

Is this a game that needs a NES 2.0 header perhaps?

**Comment by greyrogue** [comment]
Huh. I know I ran this before. Yep. Runs on April 21 2019 release.

**Comment by MP2E** [comment]
fixed as of #109
