### ISSUE TITLE
Gall force fds : error 07

### ISSUE THREAD

**Issue by funkycochise** [MiSTer-devel/NES_MiSTer#112]
at stage 2, the game displays error 07

**Comment by James-F2** [comment]
I have played to level 5, killing 2 bosses.
No problem at all.
Please use manual Disk Swap: FDS Button.
Also, make sure you don't accidentally press it during gameplay.

**Comment by Kitrinx** [comment]
Seems this error is caused by accidentally changing the disk side (pressing the button) during a level, as it checks the disk between each level. If you change the side, it will be unable to continue.

**Comment by funkycochise** [comment]
disabling auto fds swapping solved the problem.
