### ISSUE TITLE
FDS Disk Change/Loading Issues 7-19-19 

### ISSUE THREAD

**Issue by carnage-asada** [MiSTer-devel/NES_MiSTer#122]
I tried out a few FDS games today and ran into some problems. I tried both manual and auto disk change modes.

Cannot Detect Disk Change:
Michael English Daibouken
Elements of the Shaolin Fist - Ankoku no Maou
Koneko Monogatari

Stuck at Now Loading:
Kineko - Kinetic Connection - The Monitor Puzzle

Stuck at black screen:
Silviana - Ai Ippai no Boukensya

All the other FDS games work great so far!

**Comment by SegaSnatcher** [comment]
I can also confirm this issue effects Doki Doki Panic as well.  Disks will not change in either auto or button swap modes.

**Comment by sorgelig** [comment]
so it looks like some games don't expect swapping will take so short time.

**Comment by paulb-nl** [comment]
Zelda also shows an error.

Doki Doki Panic works fine with auto disc swap on release 0510.

**Comment by wwark** [comment]
I tried this game "Fuuun Shourin Ken - Ankoku no Maou (Japan)" and I have issue to change disk.
With the auto mode, It asked to set disk A.
With the FDS Button, it asked to set disk B and i tried to push the button for a long time or just one or two seconds I can't pass the screen.
It seems not detect the change.

The sha1sum is "0ff931a8716779af79d03cf64c0030e1a47e3d17  Fuuun Shourin Ken - Ankoku no Maou (Japan).fds"

Thanks,

**Comment by SegaSnatcher** [comment]
> Edit: Sorry I didn't see it is already listed in the first message.
> 
> I tried this game "Fuuun Shourin Ken - Ankoku no Maou (Japan)" and I have issue to change disk.
> With the auto mode, It asked to set disk A.
> With the FDS Button, it asked to set disk B and i tried to push the button for a long time or just one or two seconds I can't pass the screen.
> It seems not detect the change.
> The sha1sum is "0ff931a8716779af79d03cf64c0030e1a47e3d17 Fuuun Shourin Ken - Ankoku no Maou (Japan).fds"
> 
> Edit:
> Another games Stuck at Now Loading:
> 
> * Mahjong Kazoku (Japan)
> * Also the second game of "Monitor Puzzle Kineko, The - Kinetic Connection II"
> 
> Thanks,

Can you try again?

**Comment by wwark** [comment]
Update with a build from this commit https://github.com/MiSTer-devel/NES_MiSTer/commit/de499cba324e2f88b4570b37142e8adc2547978f

Cannot Detect Disk Change:
Michael English Daibouken
Elements of the Shaolin Fist - Ankoku no Maou
Koneko Monogatari

Stuck at Now Loading:
Kineko - Kinetic Connection - The Monitor Puzzle
Monitor Puzzle Kineko, The - Kinetic Connection II
Mahjong Kazoku (Japan)

Stuck at black screen:
Silviana - Ai Ippai no Boukensya

Thanks,

**Comment by mattd121** [comment]
Can confirm issue with Silviana - Ai Ippai no Boukensya.

Gets past disk swap, shows Nintendo message, then goes black & unresponsive.

**Comment by rittwage** [comment]
This is still a problem with the same games. Maybe the disk is not "ejected" long enough.

**Comment by paulb-nl** [comment]
Some of these games use their own disk functions instead of using the FDS bios so it required some major changes to make these work.

The above games should work with the attached rbf but it would be good if people can check if all the other games still work.
[NES_FDS.rbf.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/8409015/NES_FDS.rbf.zip)

The Adventures of Chatran requires manual disk swapping.

**Comment by wwark** [comment]
Thank you @paulb-nl 

With your last PR, those cases are fixed

Cannot Detect Disk Change:
Michael English Daibouken -> **Fixed**
Elements of the Shaolin Fist - Ankoku no Maou -> **Fixed**
Koneko Monogatari - The Adventures of Chatran (this games asked to set side B and push a button) -> **Fixed**

Stuck at Now Loading:
Kineko - Kinetic Connection - The Monitor Puzzle -> **Fixed**
Monitor Puzzle Kineko, The - Kinetic Connection II -> **Fixed**
Mahjong Kazoku (Japan) -> **Fixed**
Super LoadRunner 1 & 2 (last updates roms of no-intro) -> **Fixed**

Stuck at black screen:
Silviana - Ai Ippai no Boukensya -> **Fixed**

Edit:
Stuck at blue screen after change B disk
German Tanteidan MarinGumi - Maruhi Jigomar Sousa File (Japan) -> **Fixed**

I think we can closed this ticket and opened new one if we find new issues.

Great PR !!!!

**Comment by wwark** [comment]
The last release contains all fixes of issues raised by this ticket.
It could be closed Thanks !
