### ISSUE TITLE
No Good ratio for 4/3display

### ISSUE THREAD

**Issue by bilippe** [MiSTer-devel/NES_MiSTer#130]
Hello, could you redefine the ratio for 4/3 display (HDMI Mode). In fact, the ratio in 4/3 mode displays a ratio of 1.28 instead of 1.33 (4/3). For example, NeoGeo Core has a good display in proportions and Genesis too. (original mode and 304px for NG / 320*224 aspect : "Corrected ")
Nes, Snes, Sega Master System and Pc Engine display in 4/3 mode has this issue too....
Thanks in advance for a real 4/3 ratio like 20years ago!

**Comment by rikard-softgear** [comment]
I copied this from somewhere, as I think it summarises the thing quite well.

"The NES generates a 256x240 picture, yes. But it doesn't generate it with equal amounts of overscan on all sides. If you want to stretch it to fit a 4:3 screen, you have to stretch the 280x240 area that includes it to a 4:3 screen. Stretching the 256x240 to a 4:3 screen is absolutely the wrong thing to do."
https://github.com/libretro/RetroArch/issues/2837#issuecomment-207196478

Technical details: http://wiki.nesdev.com/w/index.php/Overscan

**Comment by paulb-nl** [comment]
The current aspect ratio is correct. Use the linearity test on the 240p test to check.

**Comment by bilippe** [comment]
OK ! 
Thanks for replying so fast ! 
Sorry for my english, i'm french.
