### ISSUE TITLE
Maharaja (FC):  Visual Glitches on boot. 

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/NES_MiSTer#131]
Game has visual glitches on boot and when in game is mainly a black screen with some glitched sprites.

**Comment by carnage-asada** [comment]
Also getting the same issue with both Maharaja and Mindseeker (Mapper 19)

**Comment by MP2E** [comment]
Mindseeker does seem to have a problem, but that would be better put in its own issue
