### ISSUE TITLE
NSF Clipping/Popping issues.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/NES_MiSTer#140]
Ninja Gaiden 3 NSF produces noticeable clipping/popping.  

I also noticed that audio enable volume doesn't change when switching from "Both" to "Internal" when playing games that don't have expansion audio.

**Comment by Kitrinx** [comment]
None of the nes devs have been able to reproduce this, so perhaps it was resolved in the meantime.
