### ISSUE TITLE
Twin Dragons graphics corruption

### ISSUE THREAD

**Issue by jonasongithub** [MiSTer-devel/NES_MiSTer#146]
In Twin Dragons ([https://www.brokestudio.fr/en/shop/twin-dragons-2/](url)) you encounter signs that activate a tutorial screen. Exiting out of one will result in a corrupted screen. Walking away and back restores the correct graphics.

![IMG_4706](https://user-images.githubusercontent.com/22001441/68591018-10b01b80-0490-11ea-8d09-7b2770e6ad9b.jpg)
![IMG_4707](https://user-images.githubusercontent.com/22001441/68591027-1443a280-0490-11ea-9556-6788ae429acb.jpg)
![IMG_4708](https://user-images.githubusercontent.com/22001441/68591042-1c034700-0490-11ea-85a7-b08c61525241.jpg)
![IMG_4709](https://user-images.githubusercontent.com/22001441/68591046-1e65a100-0490-11ea-9ccd-34042d80b0f5.jpg)

**Comment by MP2E** [comment]
I asked about this on the Classic Gaming Discord and @Kitrinx stated that there's no bug on MiSTer's end, the mirroring in this ROM's header is set incorrectly.

**Comment by Kitrinx** [comment]
![twindheader](https://user-images.githubusercontent.com/15653832/68593681-9d8cb200-045b-11ea-8574-14f851257598.PNG)
These are the correct header settings. You won't experience mirroring problems if you correct them.

**Comment by MP2E** [comment]
I can't test since I don't have the ROM, but I found 2 small bugs in mapper 30 that maybe fixed the issue
[NES_Test.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/3834426/NES_Test.zip)

**Comment by MP2E** [comment]
Deleted my previous message because the build I posted seemed to break other things.
