### ISSUE TITLE
Glitchy line in Kyatto Ninden Teyandee

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/NES_MiSTer#151]
This happens during the intro.  Top left of the text box there is a glitchy line that doesn't appear in any video I can find on youtube.  

Here's a video I took.  

https://www.youtube.com/watch?v=Y5EO73KRicw

**Comment by MP2E** [comment]
![Screenshot from 2019-11-23 17-46-32](https://user-images.githubusercontent.com/167708/69488066-6f26b380-0e19-11ea-8e18-bbf70ceaaa45.png)

Looks eerily similar to #149 

I'm guessing it's the same bug. Still, 2 different instances of it should help track it down

**Comment by MP2E** [comment]
Actually I take back what I said before. This happens in Mesen too!

I guess we need someone to verify this on real hardware, but the glitchy line is exactly the same in Mesen, which makes me think this might actually not be an issue.

**Comment by SegaSnatcher** [comment]
I can confirm it happens in puNES emulator too.   Hmmm, yeah I tried searching for youtube videos and didn't see this glitch.

**Comment by MP2E** [comment]
I don't have my Famicom and Everdrive handy to test but I'll be getting it in the next few days, if nobody verifies by then I'll test it

**Comment by paulb-nl** [comment]
It happens on real hardware: [https://youtu.be/H7gahwW8oRc?t=801](https://youtu.be/H7gahwW8oRc?t=801)

**Comment by SegaSnatcher** [comment]
Thanks Paulb-nl, I'll close this out.
