### ISSUE TITLE
Zoda's Revenge can't create game

### ISSUE THREAD

**Issue by wesclemens** [MiSTer-devel/NES_MiSTer#157]
Game loads. Odd boxes around text area. Can enter name but when submitting returns to game select screen without creating game file.

Core: NES_20191117.rbf
Rom: c2b74e7720e0d20e77dd371954e8834b  Zoda's Revenge - StarTropics II (USA).nes

**Comment by MP2E** [comment]
This game and the first StarTropics both need NES 2.0 headers with submapper set to 1 in order to work correctly

**Comment by wesclemens** [comment]
Interesting I will test tonight, this ROM works on the NES with an Everdrive N8. I wonder how Krikzz detected it correctly without the submapper?

**Comment by paulb-nl** [comment]
Most likely the N8 does not emulate RAM write protection. According to Nesdev leaving PRG-RAM always write enabled will remove most of the incompatibility between MMC3 and MMC6. 
https://wiki.nesdev.com/w/index.php/MMC3#iNES_Mapper_004_and_MMC6

This is of course not accurate to hardware and MMC6 also has less RAM than MMC3.

**Comment by Kitrinx** [comment]
Paul is correct. Most emulators and N8 choose to not respect the hardware accurately because it doesn't have much impact on anything, but it is technically wrong. We implement the full behavior of the hardware, requiring the correct mappers.

**Comment by wesclemens** [comment]
I was able to confirm this fixed the issue. Thanks for the help.
