### ISSUE TITLE
Kai no Bouken: The Quest of Ki display errors

### ISSUE THREAD

**Issue by wren2** [MiSTer-devel/NES_MiSTer#160]
I'm getting some major display glitches with Kai no Bouken - The Quest of Ki (Japan).nes (CRC-32 is A5E74941). I believe the game uses mapper 206. 

Screenshots:
![20200201_144908-Quest of Ki, The (Japan)](https://user-images.githubusercontent.com/54677456/73594141-97d9c200-44c8-11ea-8b40-7635627368b2.png)
![20200201_144924-Quest of Ki, The (Japan)](https://user-images.githubusercontent.com/54677456/73594142-99a38580-44c8-11ea-80d0-0358444d10b8.png)

I'm very new to MISTer in general, so apologies if I'm missing something obvious.

**Comment by paulb-nl** [comment]
Opening this rom in Mesen shows this in Tools->Log window:
```
Loading rom: Kai no Bouken - The Quest of Ki (Japan).nes
File CRC32: 0xA5E74941
------------------------------------------------------
[DB] Initialized - 15540 games in DB
PRG CRC32: 0x15249A59
PRG+CHR CRC32: 0xE1526228
[iNes] Mapper: 4 Sub:0
[iNes] PRG ROM: 128 KB
[iNes] CHR ROM: 64 KB
[iNes] Mirroring: Horizontal
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 206  Sub: 0
[DB] System : Famicom
[DB] Board: NAMCOT-3416
[DB] Chip: 118
[DB] Mirroring: Vertical
[DB] PRG ROM: 128 KB
[DB] CHR ROM: 64 KB
[DB] Battery: No
[DB] Database info will be used instead of file header.
[Input] 2 standard controllers connected
```

The iNes header is set to mapper 4 with horizontal mirroring but the database in Mesen says it should be mapper 206 with vertical mirroring.

Try to change the header with the correct settings at Tools->Debugger->Tools->Edit iNes Header.

**Comment by wren2** [comment]
That did it, thank you! Good to know that Mesen has debug features like that.
