### ISSUE TITLE
Failure to load games for a period of time after failure to load other games

### ISSUE THREAD

**Issue by Kreeblah** [MiSTer-devel/NES_MiSTer#161]
This is a bit challenging to explain, but the NES core fails to load certain games after others have failed to load.  For example, if I load `Galaxian (Japan) (Rev A)` (as labeled by No-Intro), MiSTer just gives me a grey screen.  If I then try to load a different game such as `StarTropics (USA)`, I get the same grey screen for a bit before an attempt eventually succeeds.  I doubt this is header-related, but for full disclosure, but I first noticed this while testing out some NES 2.0 headers on my games.  However, I've tried this with both iNES and NES 2.0 headers that I have, and I'm experiencing this with both header types.  Nevertheless, in case it's relevant, the specific headers I'm using are:

Galaxian iNES header: 4E45531A 01010000 00000000 00000000
Galaxian NES 2.0 header: 4E45531A 34010008 000F0707 00000000
StarTropics iNES header: 4E45531A 10204200 00000000 00000000
StarTropics NES 2.0 header: 4E45531A 10204208 10007007 00000000

This is on release build 20191117.

**Comment by paulb-nl** [comment]
Fixed with 83612c4fa6dd2d33c9cc536fb2e935ce4a020f6b. 

Invalid headers will not freeze the core anymore.
