### ISSUE TITLE
Kyoro Chan Land lock

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/NES_MiSTer#166]
Hello and thank you for this awesome piece of work.
I've run into an issue with the Japanese game Kyoro Chan Land.
After the starting screen, upon entering the first tower, the game locks.
I am unsure whether it may be my dump (it's from the ever popular everdrive set, CRC32 61202FE9) or something else, so I allow myself to report the issue.

I have also had the graphical glitch mentionned in issue #134  with Fudou Myoou Den (CRC32 6E1F3C62).
I couldn't test another dump to see if it was the dumped cartridge that was the culcript, as somebody else there mentionned they didn't have any issue.
I'm using 128MB of RAM, if that is relevant.

Cheers!

**Comment by SegaSnatcher** [comment]
It doesn't lock up on me, but it gives me a buzzy sound.

**Comment by Left-Empty** [comment]
Oh my, you were right. The odd case were hitting all the buttons on the controller was as much of the problem as a potential solution XD
Sorry for this, I'll just close it.
