### ISSUE TITLE
Missing sprite in the menu on "Saint Seiya - Ougon Densetsu (Japan)"

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#168]
Hi,

Info of the ROM:

Saint Seiya - Ougon Densetsu (Japan).nes (026C5FCA):
	PRG ROM         : 128 KiB
	PRG RAM         : 0 KiB
	CHR ROM         : 128 KiB
	Mapper          : 70
	Mirroring       : Horizontal
	TV System       : NTSC
	Has NVRAM       : False
	Has Trainer     : False
	Is PlayChoice-10: False
	Is VS. UniSystem: False

Screenshot:
https://imgur.com/a/SzRHCdz
https://imgur.com/a/DSRDsXJ

Thanks,

**Comment by SegaSnatcher** [comment]
> Hi,
> 
> Info of the ROM:
> 
> Saint Seiya - Ougon Densetsu (Japan).nes (026C5FCA):
> PRG ROM : 128 KiB
> PRG RAM : 0 KiB
> CHR ROM : 128 KiB
> Mapper : 70
> Mirroring : Horizontal
> TV System : NTSC
> Has NVRAM : False
> Has Trainer : False
> Is PlayChoice-10: False
> Is VS. UniSystem: False
> 
> Screenshot:
> https://imgur.com/a/SzRHCdz
> https://imgur.com/a/DSRDsXJ
> 
> Thanks,

So what was the fix?

**Comment by wwark** [comment]
I fixed the issue by changing the mapper. It is not good.
The menu is shown now.
I have some glitches but maybe normal I don't have the real console to check.

**Comment by tjanas** [comment]
The fix was changing it to the correct mapper of 152, yes?

**Comment by wwark** [comment]
Yes.
![image](https://user-images.githubusercontent.com/469461/93669107-dfca4b00-fa91-11ea-8485-d0ef25b11188.png)
