### ISSUE TITLE
Cheats OSD option not working for FDS game

### ISSUE THREAD

**Issue by mlc4050** [MiSTer-devel/NES_MiSTer#170]
The 'Cheats' option in the OSD menu is not highlighted/accessible for FDS games . Tested with Super Mario Brothers 2 (Japan) (DV 0).fds from the No-intro rom set & NES core release 20200308.

**Comment by SegaSnatcher** [comment]
There was never a game genie for FDS games, so they aren't supported.

**Comment by SegaSnatcher** [comment]
So, I was just told you have to match your FDS rom files to the game name within the cheat codes directory.  

If you don't mind manually changing each FDS rom to match the cheat list it should technically work.

**Comment by Kitrinx** [comment]
FDS cheats rely on the ROM names matching the cheat name, since their CRC is unreliable due to different data being saved to the flopp disk (image). Rename your rom files to match the cheat filenames and they will work.

**Comment by mlc4050** [comment]
That worked! Thank you gentlemen.
