### ISSUE TITLE
Issue Image Fight.nes (Japan) Wrong sprites and hangs

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#173]
Hi,

I want to report and issue of this game.

I force the iNES 2.0 with the new tool of @Kitrinx thanks for this good tool I manage to fix a lot of games.
Previously not working on mister also i think it is a header issue on my rom.

This game is reconised by this database https://forums.nesdev.com/viewtopic.php?f=3&t=19940&p=248796
\<game>
		\<prgrom size="131072" crc32="726EDB66" sha1="3E9E32C5BAA5D079A5891846F5EE7B8ABC8B50FE" sum16="2938" />
		\<chrrom size="131072" crc32="57961A3B" sha1="ACCCFEB431F6FD555135BC09D3CC44A7C6D2B4FC" sum16="2749" />
		\<rom size="262144" crc32="D2038FC5" sha1="E36FF62878BD9B32394E73F85D8B81139A660B38" />
		\<prgram size="8192" />
		\<pcb mapper="32" submapper="0" mirroring="H" battery="0" />
		\<console type="0" region="0" />
		\<expansion type="1" />
	\</game>
The hash sha1sum of my file produced "cdfda8e5f8aa6fd147b239fbf805043b56ccd482  Image Fight (Japan).nes" after the patch of the rom with the header of this database.
If you let the intro going the game hangs. If you try to start there is many sprites issue.

The USA game works for information. The mapper is different.
\<game>
		\<prgrom size="131072" crc32="7B1B4DD0" sha1="6AD5617CC8FAF3C43585DBA3C8B70CE73C9D6C31" sum16="0F6D" />
		\<chrrom size="131072" crc32="0DDE437B" sha1="50131BD9471C8DF9BA0209DE59B91449596621D6" sum16="EC02" />
		\<rom size="262144" crc32="058F23A2" sha1="E856AC51C79DA5F4241D49B35CA42F5197C365D4" />
		\<prgram size="8192" />
		\<pcb mapper="4" submapper="0" mirroring="H" battery="0" />
		\<console type="0" region="0" />
		\<expansion type="1" />
	\</game>

Do you think it is an issue on the database or Mister?

Thanks for your help !

**Comment by SegaSnatcher** [comment]
Can you post a picture of the issue?

**Comment by wwark** [comment]
Thank you for the confirmation !

**Comment by paulb-nl** [comment]
Fixed by #185. It requires an iNES 2.0 header with 8KB of WRAM.

**Comment by wwark** [comment]
Thanks a lot ! The test is OK no more worng sprites and hangs and my iNES 2.0 configuration is good also !
