### ISSUE TITLE
Issue Quinty (Japan).nes - Wrong sprites

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#174]
Hi,

New issue with worng sprites.
The mapper of this rom is 88 and a USA version with the name Mendel Palace (USA).nes exists working great with the mapper 4.

In the mapper 88, there is very few games. https://nesdir.github.io/mapper88.html

The sha1sum of my rom is 9e240e6bddb69082091227f9b3e05d014d05cb6a  Quinty (Japan).nes after update the header to NES 2.0.

![IMG_20200423_090802](https://user-images.githubusercontent.com/469461/80070430-38c59f80-8543-11ea-91ab-46fa974570fd.jpg)
![IMG_20200423_090751](https://user-images.githubusercontent.com/469461/80070357-20558500-8543-11ea-9eb6-11f904e7d981.jpg)

Thank you for the verification !

**Comment by paulb-nl** [comment]
Fixed by #185. There are still some minor pixel glitches.

**Comment by wwark** [comment]
Thanks a lot ! The wrong sprites is not present anymore.
Do you think it is good I let opened this ticket for the minor pixel glitches ? I can rename the title of the issue?

**Comment by paulb-nl** [comment]
Better to open a new issue for the glitches I think. It seems not related to the mapper.

**Comment by wwark** [comment]
Ok do you have some screen for those minor glitches ?
I closed this ticket !

**Comment by paulb-nl** [comment]
It shows up as flickering white dots at the top of the screen.

![20200523_175331-Quinty (Japan)2x](https://user-images.githubusercontent.com/2227984/82737177-40898700-9d2f-11ea-92c1-8dafaa01dcbe.png)

**Comment by wwark** [comment]
Ok I saw somes flickerings on different games but difficult to report.
Maybe I need to check with YT video to validate or not the flickering is normal or not.
I will open a new ticket with this screenshot thanks !
