### ISSUE TITLE
Issue - List of games using mapper 18 do not start

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#175]
Hi,

New issue for this game  Jajamaru Gekimaden - Maboroshi no Kinmajou (Japan) using the mapper 18
https://nesdir.github.io/mapper18.html
This game doesn't start when it is selected on the NES Core.

I tried another game named "The lord of king" of this mapper and it is launched without issue.

the has (sha1) of my file 909ea44da2b704e88b4058631b985897cd6ae41c  Jajamaru Gekimaden - Maboroshi no Kinmajou (Japan).nes with the header NES 2.0.

![Screenshot from 2020-04-24 09-00-57](https://user-images.githubusercontent.com/469461/80184766-7988eb80-860b-11ea-9ade-d4d891c4a3fa.png)

Thanks for the verification.

**Comment by wwark** [comment]
Another game using the mapper 18 doesn't start is Mezase! Top Pro - Green ni Kakeru Yume (Japan).nes.

The sha1sum of the rom is f33a59b1f515d9dfeafb7c8428e1d59de6876627  Mezase! Top Pro - Green ni Kakeru Yume (Japan).nes with the header NES 2.0

![Screenshot from 2020-04-26 10-43-42](https://user-images.githubusercontent.com/469461/80302527-d7076e80-87aa-11ea-80e3-37ab71c18b46.png)

Thank you.

**Comment by paulb-nl** [comment]
Fixed by #184

**Comment by wwark** [comment]
Thanks a lot @paulb-nl !
I will test with all games of mapper 18 and close this ticket after !

**Comment by wwark** [comment]
@paulb-nl All games of the mapper 18 boot without problem and no more shaking. great !
I have just one more question i don't have a real hardware to test it.

In the start screen "Jajamaru Gekimaden - Maboroshi no Kinmajou (Japan)", the M of TM seems to be cut on the right and also the shurikens on the left.
It is the same on the real hardware ?
Thanks,

**Comment by paulb-nl** [comment]
Yes it looks like that is normal.  Here is a video on real hardware:
https://www.youtube.com/watch?v=6zvjh3zBDko

**Comment by wwark** [comment]
Thank you for the checking ! Jajamaru is a great series !
