### ISSUE TITLE
Issue with Kaiketsu Yancha Maru (Japan).nes doesn't start

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#176]
Hi,

New issue for this game Kaiketsu Yancha Maru (Japan).nes using the mapper 97, it is the only game of this mapper https://nesdir.github.io/mapper97.html.
The game doesn't start. 
This mapper is on the mapper's list supported in the readme of the Nes Core.

The sha1sum of the rom with NES 2.0 header is 06fa9e97fa1c7bccea072d7b442cc40a2acc28ca  Kaiketsu Yancha Maru (Japan).nes

![Screenshot from 2020-04-26 10-00-10](https://user-images.githubusercontent.com/469461/80301636-6ad63c00-87a5-11ea-84d1-7fb7cc5f5e7b.png)

Thanks for the verification !

**Comment by paulb-nl** [comment]
Fixed by #185

**Comment by wwark** [comment]
Thanks a lot !
Test ok on my side. One more game available on Mister ! The first of 3 :)
