### ISSUE TITLE
Issue with plasma ball (japan) - some shaking on some sprites

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#177]
Hi,

I would like to report some shaking at the beginning of this game after selecting player 1 like this video https://imgur.com/a/vMEAlXq

This is the sha1sum  "c98468cca47f564fe71ae1a95eaa356fe8fc96ee  Plasma Ball (Japan).nes" with the header NES 2.0 applied
This game is on the list of the mapper 18.
![Screenshot from 2020-04-29 08-58-05](https://user-images.githubusercontent.com/469461/80568576-90f31a80-89f7-11ea-8eda-dbb24d0be6a1.png)

Sorry I don't have a device to test it on real NES or Famicom.
But in this youtube video, we don't see those shaking https://www.youtube.com/watch?v=Bpp38Xio2g4

If you think it is not a real issue you can close this ticket.

Thanks,

**Comment by wwark** [comment]
Hi,

There is on other game of the mapper 18 having some shaking.
Toukon Club (Japan) - The shaking are present during the game at the bottom bar.

**Comment by paulb-nl** [comment]
Fixed by #184

**Comment by wwark** [comment]
Thanks a lot @paulb-nl !
I closed this ticket.
