### ISSUE TITLE
Issue Galaxian (Japan) - black screen

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#178]
Hi,

When I tried to launch this game Galaxian (Japan).nes, i have a black screen and I need to reboot the core to be able to start a new game.
If i don't reboot the core, the launch of other game still imply a black screen.

![Screenshot from 2020-05-03 19-09-35](https://user-images.githubusercontent.com/469461/80920733-12d5a180-8d72-11ea-91e0-c859083630b9.png)
Sha1sum : a5f7a67a40b7a0a47a48f2280938129a1335dcaa  Galaxian (Japan).nes

Thanks,

**Comment by SegaSnatcher** [comment]
Galaxian needs an overdump and 1.0 header.

**Comment by wwark** [comment]
Thank you.
It means it will not work at all with NES 2.0 or it needs some fixes on NES core to work with NES 2.0?

**Comment by SegaSnatcher** [comment]
The 2.0 support on MiSTer can't handle a game with a PRG Rom smaller than 16KB.

**Comment by wwark** [comment]
Ok I see it is this ticket https://github.com/MiSTer-devel/NES_MiSTer/issues/71
Like @greyrogue said it needs an update of the core.
Thanks again.
Do you think we can close this ticket or rename the title of the issue and keep it on the list of issue ?

**Comment by SegaSnatcher** [comment]
Just close this and post a Feature Request for wider support of NES 2.0.

**Comment by wwark** [comment]
ok
