### ISSUE TITLE
[Feature Request] NES 2.0 support PRG Rom smaller than 16KB

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#179]
Hi,

Some games are under 16ko and the actual NES core doesn't support those games with the header NES 2.0. 

See those tickets for information's:
https://github.com/MiSTer-devel/NES_MiSTer/issues/178
https://github.com/MiSTer-devel/NES_MiSTer/issues/71

Thanks,

**Comment by paulb-nl** [comment]
Added with 83612c4fa6dd2d33c9cc536fb2e935ce4a020f6b

**Comment by wwark** [comment]
Thanks a lot.
Tested with Galaxian with iNES mapper 2.0.
