### ISSUE TITLE
StarTropics no audio and crashing

### ISSUE THREAD

**Issue by mario-64** [MiSTer-devel/NES_MiSTer#181]
I attempted to play StarTropics (USA) today and get no sound at all. Additionally, when you press Start to get to the name entry screen you hear a buzzing sound then the screen goes black. It's like the core crashes or something. This is a known good rom which works correctly on real hardware. I'm happy to provide any additional details. Please investigate. Thanks

**Comment by SegaSnatcher** [comment]
This has been brought up multiple times, please see closed issues before writing a new one.

https://github.com/MiSTer-devel/NES_MiSTer/issues/33

**Comment by mario-64** [comment]
Sorry I missed that. Just so I'm clear, I need to find a copy of the ROM in NES 2.0 format?

**Comment by SegaSnatcher** [comment]
Download and use this header editor.  

https://www.romhacking.net/utilities/1352/

**Comment by mario-64** [comment]
Thank you SO much! 
My apologies again. I'm not all that familiar with ROM headers. While I'm at it, are there any other games I need to do this on? If so, is there a list by chance?

**Comment by SegaSnatcher** [comment]
Check this link out.

http://nerdlypleasures.blogspot.com/2020/04/fixing-nes-headers-and-renaming-nes.html

**Comment by mario-64** [comment]
Excellent thanks again
