### ISSUE TITLE
Xmas 2016 crashing after splash screen

### ISSUE THREAD

**Issue by mario-64** [MiSTer-devel/NES_MiSTer#182]
This rom is freely available from RetroUSB's web site but that copy is corrupt, so instead I dumped my own cartridge via CopyNES. I tested using both Mesen and FCEUX and it plays without issue. On MISTer, however, it crashes immediately after the splash screen. This rom uses mapper 30 which is listed as supported. I am happy to perform any troubleshooting steps and can provide the file itself if needed.

![Xmas 2016 header info](https://user-images.githubusercontent.com/5170184/82381276-e9667800-99f7-11ea-8dcc-298f4e560105.jpg)

**Comment by sorgelig** [comment]
May be because it's not a Xmas yet? ;)

**Comment by mario-64** [comment]
> May be because it's not a Xmas yet? ;)

LOL

If it helps, I'm told this rom/cart uses a less common form of mapper 30 (flashable, register at $C000 only).

**Comment by paulb-nl** [comment]
Indeed it works when having the register at $C000 when the battery bit is set. :)

**Comment by mario-64** [comment]
> Indeed it works when having the register at $C000 when the battery bit is set. :)

Great! Is this something that can be fixed in the core?

**Comment by paulb-nl** [comment]
Fixed by #184

**Comment by mario-64** [comment]
> Fixed by #184

Wow thank you Paul! I'll test it out as soon as it's available :)

**Comment by mario-64** [comment]
Great work and thanks again
