### ISSUE TITLE
[Issue][FDS] Missing digits sprite on some games

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#183]
Hi,

The sprite "1" on the year 1987 is not correctly shown in this game.
The sha1sum of the file is:
ee90c6f5a121ae4ed48a473f5e2b141d89acf62c  Ai Senshi Nicol (Japan).fds

https://imgur.com/nMfDJwF

I checked different videos on youtube and this sprite is present on them.

I'm using the version "Release 20200519" of this NES Core.

Thanks,

**Comment by wwark** [comment]
I found another game "Aspic - Majaou no Noroi (Japan)" with the same sprite missing "1" on the year 1988. It is a game also for FDS

[img]https://i.imgur.com/gT6nGQt.jpg[/img]

I checked different videos on youtube and this sprite is present on them.

Thanks,

**Comment by wwark** [comment]
The issue is also present on Gun.smoke (japan) with the same sprite missing "1" on the year. It is a game also for FDS.
The price for the boss of each stage is also not shown.
Thanks,

**Comment by wwark** [comment]
The issue is also present on the game Kick and Run (Japan).
For the announce of the 1st match and the skill level (1) 2 3 4 5 (level 1 is not shonw)

**Comment by paulb-nl** [comment]
Just the "1" missing is a strange issue but I have found the cause and I am working on a fix.

**Comment by paulb-nl** [comment]
This is fixed by f1479eecba6bdfc683757721c59102cdfd3df32d

**Comment by wwark** [comment]
Thanks a lot. Yes it is a very strange issue.
