### ISSUE TITLE
[Issue] Quinty (Japan).nes - Flickering on the top of the screen

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#188]
Hi,

As proposed by @paulb-nl (https://github.com/MiSTer-devel/NES_MiSTer/issues/174), I opened this new ticket to report some flickering on the top of the screen for this game.

![82737177-40898700-9d2f-11ea-92c1-8dafaa01dcbe](https://user-images.githubusercontent.com/469461/82738127-cad4e980-9d35-11ea-81d3-b499338567c7.png)

Thanks,

**Comment by paulb-nl** [comment]
I have checked some videos but some have the flickering and some don't. Maybe some are clone consoles or it is normal for some revisions.

https://www.youtube.com/watch?v=lFjwJRsuABI
https://www.youtube.com/watch?v=IrbLHKYUt4k
https://www.youtube.com/watch?v=2PO-ZiedNu8
https://www.youtube.com/watch?v=xLI8oQB0FUA

**Comment by wwark** [comment]
Yes difficult to say ....

**Comment by greyrogue** [comment]
My Mendel Palace cart (USA version of Quinty) has this flickering.  Granted, the mapper isn't the same (USA uses MMC3, Japan uses discrete logic chips), but I'm pretty sure this happens on the original Japanese carts.  The exact pattern of noise can be more or less random (some of the time, the noise liked to be mostly above the 2UP text; probably depending on which reset cpu/ppu alignment randomly occurs), but I think this is original hardware behavior.  It would be nice to get confirmation on a Quinty cart, though.

**Comment by greyrogue** [comment]
On my real Mendel Palace cart, the noisy flickering stops when you pause the game, just like it does in Quinty and Mendel Palace on MiSTer.

**Comment by wwark** [comment]
Thanks @greyrogue for your checking.
I close this ticket.
