### ISSUE TITLE
FDS Save not loading under MiSTer_20200517 and MiSTer_20200519

### ISSUE THREAD

**Issue by rd814** [MiSTer-devel/NES_MiSTer#190]
I'm not sure if this is a core issue or MiSTer main.

FDS saves don't appear to be loading when starting a FDS title or using the load function manually for me on MiSTer_20200517 and MiSTer_20200519.  It doesn't seem to matter which FDS titles I load into the core.

FDS saves do load for me when I revert to MiSTer main release MiSTer_20200429

Core release I am using: NES_20200522

**Comment by paulb-nl** [comment]
It sounds like a MiSTer main issue if it is fixed by reverting to an older main.

**Comment by sorgelig** [comment]
which fds game supports save and can be quickly tested?

**Comment by rd814** [comment]
Metroid fds is what I used to test quickly. 

You can create a game and die by getting hit by enemies in the begining and choose an in game save from there.

Then save manually or auto in the core. Restart mister or load another game then reload Metroid fds to check if the save loads on the version of MiSTer you're testing.  Perhaps you can duplicate the behavior.

**Comment by paulb-nl** [comment]
I see it here too. It creates a save file of only 1KB.

**Comment by sorgelig** [comment]
should be fixed in new release

**Comment by rd814** [comment]
Retested and fds saves are now working as of release 20200526.  Thank you
