### ISSUE TITLE
[Issue] RPG Jinsei Game (Japan) - bad sprites 

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#196]
Hi,

The issue is on a game of the mapper 4.
![Screenshot from 2020-06-06 21-05-23](https://user-images.githubusercontent.com/469461/83952490-781d2680-a839-11ea-9d21-2b475f28b54f.png)

You will find below the sprite issue:
https://imgur.com/oZHcMQ2
The sprite issue appeared in game when you move in the town.

The sha1sum of the games is d9b43933d4aa3e6d6547c2fb21f7b0281cc218ba  RPG Jinsei Game (Japan).nes.

Thanks,

**Comment by paulb-nl** [comment]
This game is detected as mapper 118 by Mesen.

````File CRC32: 0x22CE06EF
------------------------------------------------------
[DB] Initialized - 15541 games in DB
PRG CRC32: 0x42E03E4A
PRG+CHR CRC32: 0x07D92C31
[iNes] Mapper: 4 Sub:0
[iNes] PRG ROM: 256 KB
[iNes] CHR ROM: 128 KB
[iNes] Mirroring: Horizontal
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 118  Sub: 0
[DB] System : Famicom
[DB] PRG ROM: 256 KB
[DB] CHR ROM: 128 KB
[DB] Save RAM: 8 KB
[DB] Battery: Yes
[DB] Database info will be used instead of file header.
[Input] 2 standard controllers connected
````

**Comment by wwark** [comment]
I didn't know Mesen have this tool I will check next time.
I will report the issue to the DB I used.

Thank you !
