### ISSUE TITLE
[Issue] Legend of Link - does not boot (grey screen)

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/NES_MiSTer#197]
http://www.romhacking.net/hacks/2136/

I made sure my patched ROM works in Mesen. It also worked in an older version of the core, but I tested the last 3 releases and none will boot this game.

Strangely, Rockman 4 Minus Infinity boots fine (they both are large sized MMC5 games)

**Comment by paulb-nl** [comment]
This commit https://github.com/MiSTer-devel/NES_MiSTer/commit/8d1cbe0d05eab14c6b935c1e2816bbd02455b989 seems to have caused this issue.

**Comment by MP2E** [comment]
Fixed by b61cea7863b4659ca18821e06978a44c3a8848f8

Thanks GreyRogue! :)

**Comment by wwark** [comment]
Thank you GreyRogue !
Do you know the iNes Header for this game I have some sprites issues on my side ?
