### ISSUE TITLE
Blaster Master (USA) end credits background displaying glitchy graphics

### ISSUE THREAD

**Issue by mlc4050** [MiSTer-devel/NES_MiSTer#199]
End credit background should be black, but displays glitchy graphics. Found with NoIntro rom Blaster Master (USA).nes, CRC32 BC300047

**Comment by SegaSnatcher** [comment]
Anyway you can get to that part again and post screenshot?

**Comment by mlc4050** [comment]
Here's a screenshot of the end screen (picture taken of of my TV):
![20200616_094032](https://user-images.githubusercontent.com/63271527/84789772-349f8680-afb6-11ea-8632-388e266e1992.jpg)

**Comment by mlc4050** [comment]
I found that the issue is not present on an older rom without a 2.0 Header.

**Comment by paulb-nl** [comment]
It looks like there is only 1 wrong tile. Can you open the rom in Mesen and copy the output of Tools->Log window here?

**Comment by mlc4050** [comment]
Here's the output of the 2.0 Header version of Blaster Master in Mesen 0.9.9:
------------------------------------------------------
Loading rom: Blaster Master (USA).nes
File CRC32: 0xBC300047
------------------------------------------------------
[DB] Initialized - 15541 games in DB
PRG CRC32: 0xC71C7619
PRG+CHR CRC32: 0x3F0FD764
[iNes] NES 2.0 file: Yes
[iNes] Mapper: 1 Sub:0
[iNes] PRG ROM: 128 KB
[iNes] CHR ROM: 128 KB
[iNes] CHR RAM: 8 KB
[iNes] Work RAM: 0 KB
[iNes] Save RAM: 0 KB
[iNes] Mirroring: Horizontal
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 1  Sub: 0
[DB] System : NesNtsc
[DB] Board: NES-SL2ROM
[DB] Chip: MMC1B2
[DB] PRG ROM: 128 KB
[DB] CHR ROM: 128 KB
[DB] Battery: No

**Comment by paulb-nl** [comment]
The game does not have CHR RAM so that header is incorrect. You can change the header at Debug->Edit iNES Header.

**Comment by mlc4050** [comment]
That did the trick! Thanks for your help (and lesson on iNES headers).

![20200617_124613](https://user-images.githubusercontent.com/63271527/84931824-f6c75e80-b098-11ea-8f08-76303aaf80ee.jpg)
