### ISSUE TITLE
Elite graphics corruption

### ISSUE THREAD

**Issue by sacredbanana** [MiSTer-devel/NES_MiSTer#201]
Playing Elite the screen is too far down and the lower portion of the ships in the intro render in a very corrupted fashion...

**Comment by wwark** [comment]
Elite is PAL game.
You need to set PAL in configuration of the NES core. Normally it will fixed the issue you have.

**Comment by famiclone6502** [comment]
I can confirm that this game works fine setting the console to PAL mode. There is a misleading "NTSC" prototype version of the game, which even says in-game that it's for NTSC, but it still requires a PAL console to display properly.

**Comment by Kitrinx** [comment]
Please close this issue.
