### ISSUE TITLE
Gauntlet Graphical / Gameplay Corruption

### ISSUE THREAD

**Issue by tonytoon** [MiSTer-devel/NES_MiSTer#202]
Tengen's "Gauntlet" does not appear to function correctly. I have tried both the licensed and unlicensed versions of the game.

Licensed MD5: 88f8f4f43f2cc1fc8f7c37337600b486  Gauntlet (USA).nes
Unlicensed MD5: f5f02f4b8c817647b0584202430445ff  Gauntlet (USA) (Unl).nes

The ROM is from the no-intro collection. Other ROMs in the same set appear to work fine. (Have played dozens.)

I am running in the correct region (NTSC).

Immediately upon choosing a character and starting a game, the maze has tiles in the wrong locations, enemies appear incorrectly, player can move through apparent walls, etc. Tested with all four characters.

Presently using  NES_20200526.rbf, have not had a chance to test other versions yet.

Video of game functioning incorrectly: https://youtu.be/aZKJqy55Z_Y

**Comment by SegaSnatcher** [comment]
Sounds like a bad header.
