### ISSUE TITLE
SNAC Adapter issue with Expansion Chips

### ISSUE THREAD

**Issue by twinfami** [MiSTer-devel/NES_MiSTer#203]
Found a problem with the NES core and the SNAC adapter.

It’s seems that if an NES/Famicom game uses an expansion chip(i.e MMC5, FDS, etc), the SNAC adapter will not work. 

SNAC seems to only work with those games that don’t use them. 

Tested this with Zelda FDS, Uncharted Waters, and Castlevania III.  I can even capture it on video to show it

**Comment by paulb-nl** [comment]
I tried Castlevania 3 and Zelda FDS with SNAC just now and it seemed to work fine

**Comment by SegaSnatcher** [comment]
SNAC working fine for me as well.

**Comment by Kitrinx** [comment]
Please close this issue.
