### ISSUE TITLE
Zelda Legend of Link hack not working.

### ISSUE THREAD

**Issue by patjohnny** [MiSTer-devel/NES_MiSTer#213]
Nes core Zelda legend of link hack goes to gray screen. Never loads. Used to work on previous versions of the nes core. Please help. Thanks.

**Comment by wwark** [comment]
Maybe it is the same as this issue : https://github.com/MiSTer-devel/NES_MiSTer/issues/197
The fix is not released yet.

**Comment by patjohnny** [comment]
Okay. Thanks. I’ll leave the issue open until the fix is released.

**Comment by patjohnny** [comment]
Issue is resolved after today’s update.
