### ISSUE TITLE
Games not showing up except for test

### ISSUE THREAD

**Issue by TheCodeFiend** [MiSTer-devel/NES_MiSTer#214]
I setup my SD card using the MiSTer SD Card Utility with release 20200908.  I booted the DE-10, looked around, mapped my controllers, etc.

I then followed the instructions for installation of the NES core by copying the rbf file for release 20200620 to the SD card root, creating an "NES" folder in the SD card root, and copying my games (*.nes) to that folder.  I put the SD card back in the DE-10, powered on, loaded the NES core, and when I select Load NES file, it only shows a 240p test suite.  None of the games I copied show up.

What am I missing?

**Comment by sorgelig** [comment]
either: place your games into Games/NES or remove Games/NES folder

**Comment by TheCodeFiend** [comment]
Sorry, I received a pre-built unit.  I did not realize there were 2 SD card slots.  I coped the games to the correct SD card, and all is fine.
