### ISSUE TITLE
Donkey Kong true arcade port homebrew not working

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/NES_MiSTer#217]
https://misterfpga.org/viewtopic.php?f=17&t=1271&p=12358#p12358

As mentioned here.

![image](https://user-images.githubusercontent.com/16388068/97369814-4271ec00-1873-11eb-83a3-4cd3440e958e.png)

Likely culprit could be it being an NROM (Mapper 0) yet having battery backed SRAM, which seems to require an exception in emulators. An example of a similarly configured officially licensed game is 10-yard fight which is NROM PRG-32kb CHR-8kb but no Battery Backed SRAM, and this works.

The Rom's MD5: 9D64596784A288637695D309EA7868C4

**Comment by greyrogue** [comment]
A full NES 2.0 header works with this game with latest code (it uses the Tepples/Multi-discrete mapper which supports several mappers including mapper 28 and mapper 0 - the one used here):
4E 45 53 1A 02 01 02 08 00 00 70 00 00 00 00 00
This specifies an 8KB Save RAM, which appears to support saving high scores.  If saving the RAM isn't meant to be supported, it should be:
4E 45 53 1A 02 01 00 08 00 00 07 00 00 00 00 00

**Comment by birdybro** [comment]
Confirmed NES 2.0 header works!

The hash for the 2.0 header'd one I used (I converted it using a script and the latest nes20db.xml).
CRC32 = 36038D41
MD5 = 82E3BA8A211A99725982423FC6AD035A
