### ISSUE TITLE
Typo on NES clocks documentation (?)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [MiSTer-devel/NES_MiSTer#218]
https://github.com/MiSTer-devel/NES_MiSTer/blob/master/rtl/nes.v
line 133, comment:
// Master clock speed: NTSC/Dendy: 21.477272, PAL: 21.2813696

NTSC NES, Famicom = 21.477272 MHz 
PAL NES, Dendy = 26.601712 MHz

https://wiki.nesdev.com/w/index.php/Cycle_reference_chart
https://forums.nesdev.com/viewtopic.php?f=2&t=20931

![differences](https://user-images.githubusercontent.com/13199529/97995401-82971880-1df7-11eb-87fe-3750db5ace1a.png)

**Comment by sorgelig** [comment]
it's basically the same. NES core uses the same divider for NTSC and PAL.
