### ISSUE TITLE
The Krion Conquest doesn’t work

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/NES_MiSTer#220]
The game crashes with a garbled screen right after starting it from the main title screen.

**Comment by SegaSnatcher** [comment]
Game working fine on my NES 2.0 pack.

![unnamed (3)](https://user-images.githubusercontent.com/36483667/98487341-ff573780-21e7-11eb-8c5e-c38a82d40ee6.jpg)

**Comment by bootsector** [comment]
False alarm! Thanks for confirming, @SegaSnatcher 
I did a cold reboot and it works fine now!
