### ISSUE TITLE
Battle Kid 2: Mountain of Torment — does not boot with header set to mapper 2

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/NES_MiSTer#221]
I'm honestly not sure if this is a case of core working as designed or an issue worth fixing.

Battle Kid 2: Mountain of Torment is a homebrew game released commercially on cartridges in 2012. According to Nesdev wiki, its game cart used a newly designed UNROM 512 board, which usually corresponds to mapper 30. This game however did not use most of advanced features of the board, and when this game was eventually dumped it was given a header corresponding to mapper 2.

As such the dumped rom file (**CRC-32**: 4916DC6D, **MD5**: E2F7EBAC24AB505D46350A239E10E449) has the following header:
![battlekid2](https://user-images.githubusercontent.com/70150033/101248257-e5990980-372d-11eb-86db-a1a4bc52e654.png)
The problem is that this particular rom does not boot on MiSTer NES core, resulting in a grey screen. My assumption is that it's probably related to 512KB of PRG ROM, which as far as I know is off spec for UNROM.

I managed to circumvent this by manually changing the header from mapper 2 to 30, and the rom with a new header successfully booted on MiSTer, working as expected after a brief check. Nevertheless, as the game works properly on emulators with mapper 2, as originally assigned by its dumper, it may be worth to look into this issue.

**Comment by Kitrinx** [comment]
You should advise the distributor of this game to set the proper mapper in the header of the game. It's a mapper 30 game, and uses a value invalid for mmc1. Rather than allowing invalid parameters for a real official mapper, it would be best to simply use the correct mapper for the game.

**Comment by Thelypody** [comment]
Release 20210430 added large PRG ROM support for mapper 2, making Battle Kid games playable with roms set to mapper 2 instead of mapper 30. This issue in now resolved. Thanks to everyone involved with this core.
