### ISSUE TITLE
MMC1 SXROM Support

### ISSUE THREAD

**Issue by nintendesi** [MiSTer-devel/NES_MiSTer#222]
Hello, I'm writing about an issue regarding the variant of MMC1 that is currently being used for the NES core of the MiSTer project. I often play a romhack called Z1M1 (Zelda 1/Metroid 1 Crossover), and it uses SXROM. This nesdev link should provide the relevant information on the SXROM: https://wiki.nesdev.com/w/index.php/MMC1#SOROM.2C_SUROM_and_SXROM. When I tried to play the game on the NES core of the MiSTer, I was shown the following screen: https://cdn.discordapp.com/attachments/673454160850452481/790379979451531284/Screenshot_2020-12-20_184645.png. Fixing this problem would not only benefit other people like me who want to play this romhack on the MiSTer FPGA, but also would provide support for an official Nintendo game on the hardware: a release of Final Fantasy 1 & 2 multicart which also requires SXROM to function. I went looking in earlier reported issues, and I found this: https://github.com/MiSTer-devel/NES_MiSTer/issues/139. It's unclear to me if this is related to the current case I'm writing about, but I wanted to write in that I have looked to see if this issue has been brought up before.

Thank you very much for all of your help with putting together this project, and I hope that this bug report helps the MiSTer project improve!

**Comment by paulb-nl** [comment]
Support for SXROM has been added https://github.com/MiSTer-devel/NES_MiSTer/commit/44e592cdc776b0cc7da9678bdcd6faa6ef959765

**Comment by wwark** [comment]
Thanks @paulb-nl !

**Comment by SpaceNeurosis** [comment]
Thanks so much for getting this change in so quickly @paulb-nl! 

I'm really excited to try out this change and have been working through building the rbf myself but it looks like I still have some trial and error ahead of me.

What is the usual timeline for new rbf files to be released in the repo? Definitely not trying to rush anything, I'm just curious in case I'm not able to build my own rbf successfully.

**Comment by nintendesi** [comment]
I sincerely appreciate all of your help, thank you so much!

**Comment by ghogan42** [comment]
It's not hard to build a core. You need the free version of Quartus (ideally Quartus Lite 17.02 I think) and the Cyclone V support package. And then you open the project file and press "Compile".  But if you have a newer major version like quartus 18 then you have to rename a project file...

But there can be months between core releases when things are moving slowly. So in case you have trouble building a core I have uploaded one here that you can test: [NES Core with SXROM Support](https://drive.google.com/file/d/1rDSGSgrd_g_fkeWcZtDJF-KRaa3yO6Ok/view?usp=sharing)

**Comment by SpaceNeurosis** [comment]
Thanks for the info and the built core! I managed to build an rbf using Quartus Lite 17.02, targeting Cyclone V but I must have missed something because the screen would just go black when I tried loading it. I'm still learning a lot so want to try figuring out why it went wrong.

Thanks again!

**Comment by SpaceNeurosis** [comment]
Just to follow up, Z1M1 seems to be working perfectly with the updated core. I was also able to get the core I had built working. 🎉 

Thanks again!
