### ISSUE TITLE
Solstice - The Quest for the Staff of Demnos (USA) - Sprite issue

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#224]
Information on the rom : sha1sum 0bd88ae9bcbc21a08899fd37448acf3d49bb08a7

Sprite issue below with extra sprite set on:
![image](https://user-images.githubusercontent.com/469461/103167891-57490c80-482f-11eb-8b89-10a6685af5aa.png)

The sprite issue is not present in this YT video (https://www.youtube.com/watch?v=ScW77tAMOgE)
![image](https://user-images.githubusercontent.com/469461/103167920-86f81480-482f-11eb-9e56-661065992d3f.png)

The issue is available in last official release and last updates of Rambo1.

Thanks,

**Comment by SegaSnatcher** [comment]
Turn off extra sprites for this game.    This game loads fine for me most times I've tried, but there was a couple occasions where some of the pixels were shifted to the right.   It's rather odd behavior.

**Comment by wwark** [comment]
Thank you. I think extra sprite will not have this kind of behaviour that's why I opened this issue.
Maybe better to set off to be sure to have correct behaviour.

**Comment by wwark** [comment]
extra sprite option can have graphical glitches. ticket closed.

**Comment by SegaSnatcher** [comment]
Just wanted to provide an update, I've gotten this bug via Rambo test build without extra sprites enabled.  Sometimes some of the pixels will be shifted to the right, it seems very random when it will do this.  

I will test latest official release to see if this ever happens without extra sprites enabled as well.
