### ISSUE TITLE
Would it be possible to add the Magnum palette ?

### ISSUE THREAD

**Issue by Chocobobobo** [MiSTer-devel/NES_MiSTer#227]
Thanks in advance, all infos are here:
https://www.patreon.com/posts/nes-composite-45695288?utm_medium=social&utm_source=twitter&utm_campaign=postshare

And the palette can be downloaded from here:
https://drive.google.com/file/d/1Mq874N-yzWB6RBo0g-KDIkGn2les7GUt/view?usp=sharing

**Comment by SegaSnatcher** [comment]
You can load it via the custom palette option.

**Comment by Chocobobobo** [comment]
Yes, this is how I use it. My request was more to implement it into the official repo, since it is really good.

**Comment by birdybro** [comment]
I just added it to the zip file in my PR. Given that FirebrandX suggest the Sony-CXA be deprecated now (and Wavebeam+PC-10 are already integrated into the built-in palettes options), I suggest Sony-CXA be replaced with Magnum in the OSD. I would do it myself but it will probably take awhile to figure out how that was coded and @Kitrinx is the expert on the palettes and how they are entered.

**Comment by SegaSnatcher** [comment]
Sony CXA is not deprecated.  FBX didn't create that palette, he only made an alternative.

**Comment by birdybro** [comment]
Ah my bad, I misunderstood FBX's patreon post. No problem!

**Comment by Kitrinx** [comment]
My plan is to only remove hard-baked palettes now that palette loading is a thing, with only 1-2 hard-coded palettes. So if I touch them, it will only be to remove.

**Comment by sorgelig** [comment]
I don't get all this mess with palettes at all. It should be a single predefined set.
I understand that in every core you can replace the colors, but it doesn't mean every core must become a Christmas Tree.

**Comment by Kitrinx** [comment]
People will complain forever if you force them to use only one. People release new ones all the time and make lots of fireworks about it on social media, so inevitable people will ask. But, there is also no need for a dozen baked in ones. Just let people load and have a couple of good integrated options.

**Comment by SegaSnatcher** [comment]
Wait, does the MiSTer updater download a Palette Zip?   If not, I think having the current options in the menu would still be beneficial.

**Comment by Chocobobobo** [comment]
Thanks Birdybro!
