### ISSUE TITLE
Incorrect Save Data Loaded When Switching ROMs

### ISSUE THREAD

**Issue by nintendesi** [MiSTer-devel/NES_MiSTer#228]
Hello, I'm writing in about an issue I've been experiencing regarding save files on certain cores of the MiSTer. I haven't checked all of the cores, but I have experienced this on the NES and the GBA cores, and I have not noticed this issue on the SNES core when experimenting with Super Metroid Randomizer.

I use the MiSTer to play randomizers often. Usually I generate a bunch of seeds of a randomizer at once, and then load them all in the MiSTer at one time. [Here is an image](https://cdn.discordapp.com/attachments/673454160850452481/795188448046088192/1_NES_Games.png) of what my NES directory looks like in the MiSTer, for the Zelda 2 randomizer. For the purpose of this report, I ran Z2_SEED_A and played for a few minutes. I found a Heart Container, which (brought me to a total of five squares of health). I also leveled up to Attack level 2, Magic level 2, and Life level 3, at which point [I saved the game in Z2_SEED_A](https://cdn.discordapp.com/attachments/673454160850452481/795188481067450408/3_Zelda_2_Seed_A.png). I also checked the directory for saves in the MiSTer, and I [observed this](https://cdn.discordapp.com/attachments/673454160850452481/795188470393470986/2_NES_Save_Directory.png). I then opened the MiSTer menu and [switched to Z2_SEED_B](https://cdn.discordapp.com/attachments/673454160850452481/795188486491734047/4_Zelda_2_Seed_B.png). As shown, the save data from Z2_SEED_A carried over to Z2_SEED_B when I opened the file, retaining the same file names and levels, along with items like the Heart Container, Hammer, and Reflect spell (the items are not shown in the image).

I also tested a third seed, Z2_SEED_C, which had different parameters in the randomizer. In the randomizer settings, all files in Z2_SEED_C should start out with 2 squares of health (instead of the standard four squares of health). I [ran Z2_SEED_C](https://cdn.discordapp.com/attachments/673454160850452481/795188492267290654/5Zelda_2_Seed_C.png), as I did with Z2_SEED_B, and I observed that the player was given [five squares of health](https://cdn.discordapp.com/attachments/673454160850452481/795188500805976084/6_Zelda_2_Seed_C_Image_2.png). Based on what I had observed in Z2_SEED_B, I was expecting the player to have at most three squares of health (the two squares of health that the randomizer grants the player, plus the Heart Container item from the other seed), but instead it seems like all of the save data was copied over from Z2_SEED_A to Z2_SEED_B and Z2_SEED_C. 

At this point, I checked [File 2 of Z2_SEED_C](https://cdn.discordapp.com/attachments/673454160850452481/795188504623579146/7_Zelda_2_Seed_C_Image_3.png), and the beginning health was set to [four squares of health](https://cdn.discordapp.com/attachments/673454160850452481/795188512889634846/8_Zelda_2_Seed_C_Image_4.png). Then, within the game of Zelda 2 itself, [I deleted a game file](https://cdn.discordapp.com/attachments/673454160850452481/795188516383358996/9_Zelda_2_Seed_C_Image_5.png) (the third file, formerly titled FPGA, and [renamed it NEW FILE](https://cdn.discordapp.com/attachments/673454160850452481/795188521627287562/10_Zelda_2_Seed_C_Image_6.png)), and when I opened the game it provided the player with the [desired 2 squares of health](https://cdn.discordapp.com/attachments/673454160850452481/795188529000742922/11_Zelda_2_Seed_C_Image_7.png). Finally, I opened up the save directory on the MiSTer after all of this, and I [observed the following](https://cdn.discordapp.com/attachments/673454160850452481/795188532918353940/12_NES_Save_Directory_Image_2.png).

I also checked this issue on other randomizers, and the results became much more unpredictable when it came to things like overworld spawn placement for some seeds. If I switch games by going to the Cores menu and then selecting a different seed, then I can avoid this issue, but I wanted to submit the issue, since I hadn't seen anyone mention it before. Thanks again for all of your help!

**Comment by paulb-nl** [comment]
The core won't touch the save data during rom load unless there is a sav file. So just make sure there are save files for every different seed rom and the save data won't be carried over.

Don't load a new rom too quickly after opening the OSD if you are using Autosave because it might be still saving to the sdcard and bad things can happen.
