### ISSUE TITLE
[Feature Request] 5x integer cropped scaling option.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/NES_MiSTer#230]
I posted a thread at the official MiSTer forums explaining why I believe this would be a welcomed feature and others chimed in as well. https://misterfpga.org/viewtopic.php?f=29&t=1497

At least two MiSTer devs have proven the scaler can handle 5x vertical cropped scaling no problem, just need to figure out best way to implement it from a user standpoint.  

Whether this becomes an option in the actual core menu, or a custom ini setting, I know myself and others would really appreciate this.  It is the last thing the MiSTer scaler could use to be fully featured.  

This feature would also work well on other 240p console cores such as Genesis and SNES, but for now I'll just keep this request for NES core.   Thank You to anyone who considers this.

**Comment by Kitrinx** [comment]
I have foundations for this in an outstanding branch, as you already know from Discord.  Please don't make any changes relating to this feature request at this time.

**Comment by SegaSnatcher** [comment]
This feature was implemented, thank you.
