### ISSUE TITLE
Loud popping sound(s) when rom is first loaded

### ISSUE THREAD

**Issue by retrocaster** [MiSTer-devel/NES_MiSTer#232]
Often when a rom is first loaded there's a pretty loud popping sound. This only occurs with the NES core, and it sounds like it's related to the APU rewrite that was done awhile ago.

**Comment by bellwood420** [comment]
I also experience popping noise when loading ROM.
I did some digging with SignalTap.

#### Before #194 and #200, when there is no sound:
|Signal|Value|
----|----
|APU output (`sample_apu`)|`0x0000`|
|Inverted APU output (`sample_inverted`)|`0xFFFF`|
|Mapper 0 output mixed with APU output (`sample_ext`)|`0x7FFF`|
|jt49_dcrm2 filter output (`sample_signed`)|`0x0000`|
|Final output|`0x0000` (Signed output)|

#### After #194 and #200, when there is no sound:
|Signal|Value|
----|----
|APU output (`sample_apu`)|`0x3AE0`|
|Inverted APU output (`sample_inverted`)|`0xC51F`|
|Mapper 0 output mixed with APU output (`sample_ext`)|`0x628F`|
|jt49_dcrm2 filter is removed||
|Final output|`0x628F` (Unsigned output)|

When loading a ROM, audio output is muted (audio output to `0`) while `reset_nes` is asserted and for a while after it is deasserted.
So a sudden step change of DC offset from `0` to `0x628F` is causing popping noise I think.

**Comment by bellwood420** [comment]
Also checked outputs of `IIR_Filter` and `DC_blocker` in framework.
IIR 1-tap `DC_blocker` cannot handle the step change. 

![output](https://user-images.githubusercontent.com/50853463/107850845-ed211100-6e48-11eb-92ce-596e4ad99b2e.png)

**Comment by bellwood420** [comment]
Muting to `0x628F` can be used for most mappers but is not perfect for all.
