### ISSUE TITLE
Something disables NTSC/Dendy/PAL resolution change

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/NES_MiSTer#234]
When I set [NES] in MiSTer.ini to ...

vscale_border=64
custom_aspect_ratio_1=1792:1440	; slightly wider than original
custom_aspect_ratio_2=1792:1680	; larger but a lot taller than original

... and change to NTSC the resolution stays on 256:240 instead of switching to 256:224.

It works, though, when I set the ratio to 'Original'.

Perhaps the custom ratios overrides the NTSC setting by mistake?

I have these general settings:

vsync_adjust=2
refresh_min=56
refresh_max=63

**Comment by Kitrinx** [comment]
I don't understand this issue, the number of lines is not related to aspect ratio. It all seems to be working properly.

**Comment by dfilskov** [comment]
So for you the core actually does use 256:224 when you switch to (or use) NTSC in the OSD even if you add this to MiSTer.ini:

vscale_border=64
custom_aspect_ratio_1=1792:1440
custom_aspect_ratio_2=1792:1680

?

**Comment by Kitrinx** [comment]
How are you measuring the aspect ratio it uses?

**Comment by dfilskov** [comment]
I don't measure it. I just looked at the resolution that MiSTer writes in the pop-up and realized that it wasn't 256:224 as it should be in NTSC but 256:240 instead (if I'm not mistaking).

**Comment by Kitrinx** [comment]
the resolution is the resolution, it has nothing to do with aspect ratio. Aspect Ratio is how mister's HDMI scaler chooses to scale the resolution to fit on your modern display.

**Comment by dfilskov** [comment]
Yes, exactly - so it must be a bug that it won't use the proper original NTSC resolution simply because I change the scaling.

**Comment by dfilskov** [comment]
What I chose was  NTSC and expected it to use 256x224. But it used 256x240 in NTSC mode. That's not a bug?

**Comment by Kitrinx** [comment]
no, 256x240 is the resolution of NES in NTSC mode. You can crop it with the option "crop overscan" down to 224 if you wish. This is disabled always for PAL I believe since it shows up to 240 lines before overscan.

**Comment by dfilskov** [comment]
Oh I see! - so for some rason it must have turned off cropping when I set aspect ratio to other that 'Original'. That might be the issue that I encountered.

**Comment by dfilskov** [comment]
I better check this behaviour again.

**Comment by Kitrinx** [comment]
I'm closing this issue because it seems stale and can't be reproduced. If this is still a problem please re-open the issue.
