### ISSUE TITLE
Corrupted graphics on Kai no Bouken: The Quest of Ki

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/NES_MiSTer#236]
No-Intro vanilla ROM. Graphics are garbled during game play.

**Comment by wwark** [comment]
Which corrupted graphics do you have ?
I tried mine with this configuration and I don't have graphics issue for the moment.
![image](https://user-images.githubusercontent.com/469461/109867605-fbec2e00-7c66-11eb-91c2-7b47f81c0df8.png)

Thanks,

**Comment by bootsector** [comment]
What's the original mapper reported by that tool? Maybe it just needs a mapper change in the header.
This is what I get:
https://cdn.discordapp.com/attachments/806759728885006356/816770521110675506/IMG_6851.jpg

**Comment by wwark** [comment]
I don't have this corruption ...
I used a set of iNES 2.0 for my NES games and this one used the mapper 206.
I don't know which is the nes mapper for standard iNES.
For better compatibility, it is recommanded to use iNES 2.0.

You could use this script to convert your rom https://github.com/Kitrinx/NES_Header_Repair
and this tool to verify your rom http://www.romhacking.net/utilities/1352/

**Comment by bootsector** [comment]
This is a bad header issue (can't trust No-Intro default headers). Closing this.
