### ISSUE TITLE
Graphic (mapper?) issues on Dragon Slayer 4

### ISSUE THREAD

**Issue by mathieulh** [MiSTer-devel/NES_MiSTer#237]
Dargon Slayer sprites do not display properly as shown in the image below

![A7itzQK - Imgur](https://user-images.githubusercontent.com/203427/110354135-1db72d80-8038-11eb-8b3b-00628ae74b98.jpg)

**Comment by Kitrinx** [comment]
Your rom's header is incorrect. this game works fine. Run my header repair tool on your rom collection.
![dragon slayer 4](https://user-images.githubusercontent.com/15653832/110354522-41618000-8006-11eb-9d0b-346dd05bd351.PNG)

**Comment by mathieulh** [comment]
Indeed it was a bad dump, closing the issue.
