### ISSUE TITLE
Alwa's Awakening NES demo errors at launch with mapper error

### ISSUE THREAD

**Issue by eturquin** [MiSTer-devel/NES_MiSTer#239]
I get the following message at launch, then garbage contents:
![File_000](https://user-images.githubusercontent.com/16614161/112534942-fee0c700-8dab-11eb-9dd7-bb7f3b3001f0.jpeg)

Happening on version 976 of the demo rom, freely available for download here:
https://eldenpixels.itch.io/alwas-awakening-nes

The same page mentions (at the bottom) the use of an extended mapper 2 with support for 512k, and yet the error message mentions mapper 1. I'd guess this specific mapper is not supported by the core, or the auto-detection is misled by the rom?

**Comment by Kitrinx** [comment]
I'll investigate, but it seems the author decided to throw following mapper standards to the wind, which is unfortunate.

**Comment by bbbradsmith** [comment]
It should have said mapper 2, not 1.

The only thing nonstandard is conventional PRG-RAM at $6000, which no older mapper 2 games had. It does specify this in the header, but most emulators ignore iNES 2 headers.

**Comment by thehughhefner** [comment]
What is the status of this?
