### ISSUE TITLE
VS Super Mario Bros freezes instantly

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/NES_MiSTer#241]
**VS Super Mario Bros** freezes instantly on boot - like this online emulation:
https://arcadespot.com/game/vs-super-mario-bros/

![image](https://user-images.githubusercontent.com/15096058/113830485-f5316900-9786-11eb-8d17-1bfeba254f6f.png)

**Comment by Kitrinx** [comment]
Vs System is not implemented

**Comment by dfilskov** [comment]
Oh I didn't know it wasn't a standard NES game. Thanks!

https://www.mariowiki.com/VS._System
