### ISSUE TITLE
Contra visual errors when dvi_mode=8 set

### ISSUE THREAD

**Issue by dukesilverfan** [MiSTer-devel/NES_MiSTer#25]
I have tested over 100 games on the NES core, and all of them work fine in the default video mode, and with dvi_mode set to '8 - 1920x1080@60', with the exception of Contra.

When loading Contra in 1920x1080@60, there are graphical errors on the loading screen, and then when the first stage begins, the entire screen as garbled graphics, and gameplay is not possible. Returning back to the default dvi_mode fixes this issue completely.

I have not been able to replicate this on any other games, or any other cores.

**Comment by dukesilverfan** [comment]
Release 20190121 changed the behavior for Contra, but it is still broken. Instead of garbled graphics now, the screen is all black except the player 1 character. 

Switching back to the default video mode fixes this.

**Comment by James-F2** [comment]
Works perfectly fine here with dvi_mode=8.
Please check your rom, it may be corrupt.

**Comment by dukesilverfan** [comment]
Can you share the hash of the rom you are using to help? I have tried the [!] rom for both US and Europe, and it behaves the same as described above, even on the newest NES_20190321.rbf release. 

I was able to run the Japanese version of Contra without trouble, and I verified that Super C works fine, but every single version of Contra for US and Probotector for EU fails when set to dvi_mode = 8.

**Comment by dukesilverfan** [comment]
This was solved by adjusting the "Invert Mirroring" option. For some reason the US version handles this memory allocation differently than the Japanese rom. Either way, this can be fixed with settings, so this issue is being closed.
