### ISSUE TITLE
On some games Music gets Volime down and Up

### ISSUE THREAD

**Issue by diettelo** [MiSTer-devel/NES_MiSTer#257]
Some Games Like Felix the Cat, Wizard and Warrior changes Music Volume down a bit and up after few seconds. Like a Dj does effects with volume controller.

**Comment by Kitrinx** [comment]
turn off auto volume on your tv

**Comment by diettelo** [comment]
No i got no auto volume turned on.
Uts only on some games and only nes core. Playstation 4 or other mister cores works.

I see if i can grab the audio and record it
