### ISSUE TITLE
Graphical glitches in Zelda II - The Adventure of Link

### ISSUE THREAD

**Issue by BarbieOnWeed** [MiSTer-devel/NES_MiSTer#258]
Zelda II - The Adventure of Link has graphical glitches.
Both PAL and NTSC, only the GameCube Edition works all the time.
Sometimes a different version works, next time it wont. Really strange.
Dont have any Game Genie codes activated.

Zelda II - The Adventure of Link (Europe)                                          CRC: 2032B947         (dont work
Zelda II - The Adventure of Link (USA) (GameCube Edition)             CRC: 2A4BD123        (work)
Zelda II - The Adventure of Link (USA)                                              CRC: 19133F4D         (dont work)

![IMG_20210630_221511](https://user-images.githubusercontent.com/52424890/124025725-181f9200-d9f1-11eb-8205-b800a6efa2d7.jpg)

**Comment by Kitrinx** [comment]
When submitting a bug report please be sure you do the following:
1) clearly define the problem and the circumstances in which it arises. eg "the sprite are missing for the graves when entering the kings tomb.
2) detail the steps required to reproduce the problem
3) provide any relevant savestate or save games to assist in getting up to the part of the game in which the problem occurs.

In your case please also verify that your ram is working correctly by running the sdram test core. All revisions of the game appear to work correctly for me with no obvious glitching after a short time played.

**Comment by BarbieOnWeed** [comment]
Well... it turns out the Zelda 2 roms got corrupted somehow.
Deleted all, and now they work as normal. :)
Sorry for the trouble!
