### ISSUE TITLE
Default location option for FDSBIOS.bin

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [MiSTer-devel/NES_MiSTer#26]
In addition to being able to load FDSBIOS.bin manually, could a default location for it be set? So if you load an .FDS ROM and the core knows that FDSBIOS.bin is in /NES, it could boot the BIOS first to save the user from having to load it manually each time. 

Another location possibility could be /bootrom

**Comment by wesclemens** [comment]
@sorgelig 
Hasn't this issue been resolved?

**Comment by sorgelig** [comment]
yes. it's already fixed in latest release.
