### ISSUE TITLE
Improper inputs read with SNAC adapter and input display in place

### ISSUE THREAD

**Issue by xexzy** [MiSTer-devel/NES_MiSTer#260]
When attempting to use an input display, such as retrospy, and a SNAC adapter with the NES core, improper inputs are read. With one controller, all buttons were read as being pressed, another controller resulted in various buttons other than what was pressed, and another controller resulted in no inputs being read. If an input display is not in place, the SNAC adapter works. The input display also functions properly when plugged into my NES or into a USB adapter then plugged into the MiSTer as a USB controller. 

Additionally, the Genesis and SNES cores do not have this issue and I am able to utilize an input display and the SNAC adapter on these cores.

**Comment by Kitrinx** [comment]
I suggest you report this issue with retrospy. NES accessories work with the core, and this is the scope of the feature.
