### ISSUE TITLE
Misaligned scrolling in Super Mario Bros. 3 bonus game

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/NES_MiSTer#265]
In Super Mario Bros 3, in the bonus game where you need to align 3 scrolling layers to form a shape, the scrolling is incorrectly misaligning a line per scrolling section.

![A817FBD0-6227-40F6-B530-FD48827C9B11](https://user-images.githubusercontent.com/86253908/130545822-d1fc3ab4-8355-4f47-8775-c0a407f7c63f.jpeg)

This absolutely does not happen on real hardware.

**Comment by Kitrinx** [comment]
This misaligned row does appear to exist on original hardware.
![IMG_20210824_020850038](https://user-images.githubusercontent.com/15653832/130566571-7f15404d-caa9-4eb6-8ca7-f378c488ebc3.jpg)

**Comment by Kitrinx** [comment]
![IMG_20210824_023507083](https://user-images.githubusercontent.com/15653832/130569116-d1fbb692-1320-472f-a32c-edd0becd7532.jpg)

**Comment by AtomicShroom** [comment]
Well I'll be damned!  I was SURE it wasn't there, then I checked and it's there! What the hell. 

My bad. I'm closing.
