### ISSUE TITLE
Broken graphics in _Felix the Cat_

### ISSUE THREAD

**Issue by jlancaster86** [MiSTer-devel/NES_MiSTer#271]
The graphics in _Felix the Cat_ have been broken since release 20210926, having a kind of ghosting/halo effect. The game plays properly in the 20210910 release.

This game is known for using colour emphasis for dimming the screen, so the recent change to how the core handles colour emphasis may be the culprit.

Release 20210927 (Wrong): ![20210927](https://user-images.githubusercontent.com/60334315/135618671-6490a266-4b86-49ac-ba3f-25c53070f0a8.png)

Release 20210910 (Right): ![20210910](https://user-images.githubusercontent.com/60334315/135618675-42ed3e4c-d4ae-4d5b-8567-8e1b92b92910.png)

**Comment by SegaSnatcher** [comment]
Great catch.  I actually play this game using the brightness hack that gets rid of the dimming, so I wouldn't have caught this.

**Comment by sorgelig** [comment]
i will fix it

**Comment by sorgelig** [comment]
try this build:
[NES.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/7269021/NES.zip)

**Comment by SegaSnatcher** [comment]
That test build seems to fix the issue on my end.
