### ISSUE TITLE
FDS Bios (boot0.rom) incorrectly loading at core startup instead of only when a FDS game is loaded.

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/NES_MiSTer#279]
Change seems to have happened with a recent update.

Previously boot0.rom would load automatically *only* when a FDS game was loaded, as per the readme.  

Now the bios loads automatically when the core starts, and has an annoying repeated noise until you select something.

Please revert this back to the previous behavior so only a grey screen comes up when the core loads, and boot0.rom is just automatically loaded whenever a FDS game is selected.

**Comment by birdybro** [comment]
Yup, @bootsector brought this to my attention, I tested it (as I normally have a boot2.rom anyways) by renaming my boot2.rom to boot2bak.rom and I see the same behavior.

**Comment by jlancaster86** [comment]
Honestly, I kinda like it booting to the FDS BIOS (and wouldn't mind it being an option), but that sound is maddening.

A workaround is to name an invalid file to "boot1.rom" and the core will default back to the grey screen. Copying "boot0.rom" to "boot1.rom" will work, as too will renaming a text file (the file just can't be blank, or else the core skips it and defaults back to the FDS BIOS).

**Comment by ZReport** [comment]
Cosigning @birdybro and @jlancaster86, adding an empty boot2.rom clears up this issue.  Might be a good mid-way fix to just commit an empty boot2.rom so that it's pulled in with future updates.

**Comment by sorgelig** [comment]
next release will fix this problem.

**Comment by M-Walrus** [comment]
Confirmed this issue is fixed.  Closing issue.

@jlancaster86 the core's readme has information already on how to boot directly to the fds bios if you would like to in the future.
