### ISSUE TITLE
Ai Sensei no Oshiete - Watashi no Hoshi (Japan).nes unable to boot.

### ISSUE THREAD

**Issue by Hareluya79** [MiSTer-devel/NES_MiSTer#283]
game boots into grey screen. 
sha1sum 935049adf7b6be6706419904f21340f6b09ff434

**Comment by greyrogue** [comment]
The version listed in the NES 2.0 XML database seems to work:
	<game>
		<prgrom size="262144" crc32="FD3FC292" sha1="6320145A0A1D6F00DC30EA1D6C1209D16BE86D51" sum16="F381" />
		<chrrom size="131072" crc32="5C2291D9" sha1="E675696BD83A8E80F8EA352AC6C6CD80FFBC6956" sum16="CC7A" />
		<rom size="393216" crc32="283AD224" sha1="91CECCFCAC90E417E9AEE80E8F7B560A20EB33CC" />
		<pcb mapper="32" submapper="0" mirroring="H" battery="0" />
		<console type="0" region="0" />
		<expansion type="1" />
	</game>

**Comment by Kitrinx** [comment]
this seems to be an issue with the OP's mapper settings, so i'm going to close it for now
