### ISSUE TITLE
Autosave no longer working.

### ISSUE THREAD

**Issue by patjohnny** [MiSTer-devel/NES_MiSTer#293]
Hi. Since update on 1/31/22, autosave no longer works. Tried on witch n wiz, the legend of Zelda, and Zelda 2 and it won’t work. No saving message when opening osd. Other cores work fine. Please help. Thanks.

**Comment by Kitrinx** [comment]
I will check, make sure it's set to on.

**Comment by Kitrinx** [comment]
Actually, it seems the label is inverted in the menu, will fix ASAP.

**Comment by Kitrinx** [comment]
this should now be resolved, please update to the latest version

**Comment by patjohnny** [comment]
Thanks for the quick resolve.
