### ISSUE TITLE
Classic Concentration

### ISSUE THREAD

**Issue by RetroDriven** [MiSTer-devel/NES_MiSTer#30]
This game has some graphical glitches after you first match two pieces. I'll try to grab some screenshots and post them here.

**Comment by RetroDriven** [comment]
![vlcsnap-2019-01-27-17h26m11s468](https://user-images.githubusercontent.com/44145655/51807772-6432df00-2259-11e9-8cac-62ec681093e3.png)
![vlcsnap-2019-01-27-17h26m54s719](https://user-images.githubusercontent.com/44145655/51807773-6432df00-2259-11e9-8b9d-9c14c97e114c.png)

**Comment by greyrogue** [comment]
Are you sure you dumped your cart correctly? This should be a mapper 2 (UxROM) game with size=128KB.

**Comment by RetroDriven** [comment]
> Are you sure you dumped your cart correctly? This should be a mapper 2 (UxROM) game with size=128KB.

This was the issue thank you.
