### ISSUE TITLE
Jikuu Yuuden - Debias (Japan) Boot into glitches

### ISSUE THREAD

**Issue by Hareluya79** [MiSTer-devel/NES_MiSTer#303]
Shasum cef4c135ccbfca551f84af1baf276e659a0c1438

**Comment by Kitrinx** [comment]
I see no problems with this game, likely an issue with your rom headers.

**Comment by Hareluya79** [comment]
Thanks Kitrinx, used your fixer to repair the header, displaying correctly now.
