### ISSUE TITLE
Solstice - White screen flashing during demo

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/NES_MiSTer#306]
During title demo, when the screen transitions from credits to gameplay, there's a brief moment where the screen flashes white.

https://streamable.com/ycr6r1

This can be seen at about 18 seconds in to this clip

This does not seem to be present in Mesen.

**Comment by Kitrinx** [comment]
what does it do on real hardware?

**Comment by Kitrinx** [comment]
nevermind, it was doing a palette write during rendering, which should be ignored by the PPU. I fixed it.

**Comment by MP2E** [comment]
Thank you! I very much appreciate it
