### ISSUE TITLE
NES menu is not appeared automatically after update all. 

### ISSUE THREAD

**Issue by suww37** [MiSTer-devel/NES_MiSTer#307]
The menu is not appeared automatically  when I run NES core  . I must press menu button when running nes core after Mister boot.  Normal after running other core.   Fix please.

**Comment by birdybro** [comment]
You must have a boot2.rom in your `../games/NES/` folder.

**Comment by Kitrinx** [comment]
I'm going to close this because I don't think it's actional from the point of view of the core. It seems to behave correctly. If someone is still having problems with the OSD not behaving the way it should we can revisit the issue.
