### ISSUE TITLE
Broken graphics in twinbee

### ISSUE THREAD

**Issue by Barbe86** [MiSTer-devel/NES_MiSTer#312]
This issue happens when you play the first twinbee game.

When you reach the stage 4 and 5 the graphics start to mess, specialy some enemies and backgrounds. I've seen this exact issue in the 90's when a played this game in a NES clone with a multi-cart, I think there's some konami chip in this specific cart that is not reported.

Thanks
![IMG20220425225344](https://user-images.githubusercontent.com/104393617/165174054-c6f82c11-68ff-4232-8771-6b8a0abb7695.jpg)
![IMG20220425225656](https://user-images.githubusercontent.com/104393617/165174061-d0ea3669-a8a9-4876-b2c5-3a092d6e5458.jpg)
![IMG20220425225858](https://user-images.githubusercontent.com/104393617/165174067-f1714337-69f6-41bf-b048-f573216f6078.jpg)

**Comment by SegaSnatcher** [comment]
Please send a save state.  I will check with my rom, thanks.

**Comment by Barbe86** [comment]
I made a savestate when graphics start to mess, the game is paused. Link to my dropbox to download: https://www.dropbox.com/s/oiivbg1h5jp7230/TwinBee%20%28Japan%29_1.ss?dl=0

**Comment by SegaSnatcher** [comment]
> I made a savestate when graphics start to mess, the game is paused. Link to my dropbox to download: https://www.dropbox.com/s/oiivbg1h5jp7230/TwinBee%20%28Japan%29_1.ss?dl=0

Just tried your savestate with my 2.0 rom and not seeing any visual glitches.  It looks like your rom has a bad header.  This is a pretty common issue with many roms that were made to work on software emulators.  I'd recommend just grabbing a 2.0 set somewhere.

**Comment by Barbe86** [comment]
I will try ASAP. Other weird thing is that the FDS version it gets black screen when you reach the stage 4.

**Comment by Barbe86** [comment]
Solved. I tried a different rom and it worked well. Thank you!
