### ISSUE TITLE
Castlevania iii whip motion glitch

### ISSUE THREAD

**Issue by patjohnny** [MiSTer-devel/NES_MiSTer#314]
Hi. The whip motion in castlevania iii seems to be glitching. You can easily notice it against most backgrounds. It’s noticeable on both hdmi and analog out. Please assist. Thanks.

**Comment by Kitrinx** [comment]
I believe this is an MMC5 related bug as it seems to be present in both different versions of the PPU that are written, maybe @paulb-nl or @greyrogue have some insights here.

**Comment by paulb-nl** [comment]
The problem was with the low tile byte fetch of the first extra sprite. `in_split_area` and `is_sprite_fetch` toggle during that time so the wrong byte was being fetched.

#315

**Comment by Kitrinx** [comment]
that makes sense. I figured the extra sprite stuff would bit us in the butt eventually, it seemed surprisingly tame to manage so far :)

**Comment by patjohnny** [comment]
Hi. I just noticed wickerwaka’s 2560x1440 build in the test builds discord seems to have fixed this glitch. Could someone double-check please? Thanks.

**Comment by Kitrinx** [comment]
This glitch is completely unrelated to that. Paul already figured out it was caused by extra sprites being turned on, and added the correct signal filtering to the NES codebase. It's already fixed, just not released yet.
