### ISSUE TITLE
wrong palettes and tiles with Donkey Kong hack

### ISSUE THREAD

**Issue by mrfpga** [MiSTer-devel/NES_MiSTer#318]
I have created a custom Donkey Kong hack which has scrambled graphics on MiSTer's NES core (NES_20220326). I believe this is not a problem with my hack, but with the core. The hack works on PC emulators (Mesen v0.9.9, FCEUX v2.6.4), on my Analogue NT Mini FPGA system and on MiSTer's SNES core when converted to a SNES rom using Nested (https://github.com/Myself086/Project-Nested/releases/). The problem with the wrong palettes and tiles on the Pie Factory stage only occurs on MiSTer's NES core:

![dkpiefactory](https://user-images.githubusercontent.com/59511741/171997087-9cf5ab08-4fa3-4e09-a13e-5217b54afc2d.png)

These are the changes I did to the Donkey Kong Original Edition rom:
```
3FE0: change FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
             FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
          to EA EA EA EA EA EA EA EA EA EA EA EA EA EA EA EA
             EA EA EA EA EA EA EA EA EA EA EA A5 18 29 02 60
             A5 15 29 08 0A 0A 6D 00 02 60 00 00 00 00 00 00

4953: change 20
          to 2C

497A: change AD 00 02
          to 20 F0 BF

4982: change D0 02 A9 7F
          to 90 02 E9 40

74FD: change A5 18 29 02
          to 20 D0 BF EA
```

What do these changes do?

[Donkey Kong (USA) (GameCube Edition)](https://tcrf.net/Donkey_Kong_(NES)#Animal_Crossing_Release) is the only version of Donkey Kong where it is possible to press Up and Down to switch between options at the title screen. I took the responsible code from this version and inserted it into [Donkey Kong Original Edition](https://tcrf.net/Donkey_Kong_(NES)#Original_Edition) which is the only version of Donkey Kong to feature the Pie Factory stage.

To save you the hassle with the hex editor, I have created a patch to recreate my hack. Just apply it to `Donkey Kong (USA) (GameCube Edition) (CRC32: 63AABE94)`: [Donkey Kong Original Edition (USA) (GameCube Edition).zip](https://github.com/MiSTer-devel/NES_MiSTer/files/8837534/Donkey.Kong.Original.Edition.USA.GameCube.Edition.zip)

**Comment by paulb-nl** [comment]
Does the Original Edition without your hack work correctly?

**Comment by mrfpga** [comment]
@paulb-nl: Yes, it works correctly without the hack.

**Comment by paulb-nl** [comment]
There are also some other changes in your hack related to bus conflicts at rom addresses 3A6, A4D and B5A. Two of those are the issue causing the wrong chr bank to be selected.

3A6: Here either chr bank 0 or 1 is written but $8001 contains 0 so only bank 0 will be selected.
![dk_wr8001](https://user-images.githubusercontent.com/2227984/172020396-1407c83c-8071-44b6-9f93-3ae631fdf66e.png)

B5A: Here bank 2 or 3 is written but $80F7 contains 2 so only bank 2 will be selected.
![dk_wr80F7](https://user-images.githubusercontent.com/2227984/172020576-c6ddbd47-f5ed-4bde-8415-462281577bc4.png)

Your hack would need some more changes if you want to prevent bus conflicts properly. You could also use NES2.0 submapper 1 which specifies No bus conflicts for CNROM: https://www.nesdev.org/wiki/NES_2.0_submappers#003:_0,_1,_2_CNROM

**Comment by mrfpga** [comment]
Dank u wel, Paul, I completly forgot about the other changes to the rom, which I applied in 2018 after reading a blog post about bus conflicts: http://nerdlypleasures.blogspot.com/2018/09/exciting-developments-for-nes-roms.html

These changes never were a problem, but apparently together with my hack they messed something up. I will now discard those changes and opt for NES2.0 submapper 1 instead, as you suggested.

I will now close this issue, as it is not core related.

**Comment by paulb-nl** [comment]
The bus conflict changes from Nerdly pleasures are incomplete. Even without your hack it will not work on original hardware (CNROM boards) or emulators that emulate bus conflicts with mapper 3.
