### ISSUE TITLE
Audio humming (DMC channel bug?)

### ISSUE THREAD

**Issue by rikard-softgear** [MiSTer-devel/NES_MiSTer#32]
It seems like PCM samples can cause an audiable hum after playback.

One good example: Start up the game Blades of Steel. Right after you hear the sample saying the name of the game, a low frequency hum (200 Hz:ish?) can be heard, and it doesn't stop until you reset the core.

**Comment by James-F2** [comment]
There is a big DC offset with NES core currently, so maybe this is part of the problem you hear.

**Comment by rikard-softgear** [comment]
Maybe so! It could very well be my TV that doesn't like the waveform being like that.

**Comment by James-F2** [comment]
The problem is not present anymore in 190307 release on all audio outputs (digital or analog).
Please confirm @rikard-softgear so this can be closed.

**Comment by dukesilverfan** [comment]
I currently notice audio hum on the NES core, that I do not experience on any other core. I was just about to post an issue until I saw this existing one.

Is it possible this was reintroduced, or not actually fixed with the 20190307 release?

**Comment by rikard-softgear** [comment]
@James-F2 Just want to confirm that this issue can be closed now.
