### ISSUE TITLE
[Issue] Blades of Steel: Halftime Animation

### ISSUE THREAD

**Issue by HiroiSekai** [MiSTer-devel/NES_MiSTer#321]
I was just playing Blades of Steel the other day, and when the halftime animation plays, it's supposed to show the Konami logo as the music ends. However, with the current newest release, instead of the Konami logo, it just shows an off-center grey rectangle.

Something to note: I got this error on the animation with a bear shooting the puck into the goal. There's an alternate halftime where you can play a few seconds of a Gradius-style minigame. Haven't tested that yet, but if I get that one, I'll update this if there are bugs there too.

https://www.youtube.com/watch?v=vHk438I2lDA
Close to the end of this video shows what the halftime should look like with the Konami logo rendering properly.

**Comment by paulb-nl** [comment]
You're using the wrong ROM. A pirate version has the konami logos removed.

**Comment by HiroiSekai** [comment]
Interesting, I didn't know that was a thing. Thanks for the info.

**Comment by Kitrinx** [comment]
I've confirmed that the correct version of the rom still plays the half time show on the most recent release of the core, so I'm going to close this issue for now. If you continue to have problems feel free to comment here.
