### ISSUE TITLE
[Feature Request] An option for proper handling of Left+Right and Up+Down

### ISSUE THREAD

**Issue by EricICX** [MiSTer-devel/NES_MiSTer#322]
Almost every other NES emulator in existence, such as FCEUX, Nestopia, and Mesen, has an option for not allowing the illegal sets of inputs, Left+Right and Up+Down. 
![image](https://user-images.githubusercontent.com/80788439/179335547-6f4caff3-94cc-4b07-a9a5-d743da28db5b.png)
![image](https://user-images.githubusercontent.com/80788439/179335477-fb53fa2c-8965-4e28-b7ba-1b9569ef87c7.png)
![image](https://user-images.githubusercontent.com/80788439/179335528-931bb3c7-500d-4f4e-9cab-670e5a9c870e.png)

Currently, the absence of this feature makes it so that the MiSTer cannot be used to speedrun certain games, so it would be nice if this was implemented.

**Comment by Kitrinx** [comment]
AFAIK nothing prevents this. You simply need a controller that physically allows it.

**Comment by Kitrinx** [comment]
I just double checked to be extra sure, nothing in the NES core will prevent any combination of buttons. It generates NES protocol directly from what it receives from the framework, so there is no actionable items here. If you feel the framework's controller handling is interfering with your ability to do this, the correct place for an issue is here: 

https://github.com/MiSTer-devel/Main_MiSTer/issues

**Comment by EricICX** [comment]
> AFAIK nothing prevents this. You simply need a controller that physically allows it.

I'm not sure if you understood what I asked. I was asking for an option for these input sequences to be disallowed with a controller that physically allows them, such as a keyboard.

**Comment by Kitrinx** [comment]
even so, it is not a core-level decision, the core just works like the hardware did, and things like SNAC cannot be restricted in such a way as they are opaque. If you want to add such a restriction, this is still a component of the framework which does all the keyboard/joystick input handling.

**Comment by EricICX** [comment]
Okay thank you, I'll ask there.
