### ISSUE TITLE
SMB2-JPN Black Screen (Freeze) after 4-4 with 20220712.rbf

### ISSUE THREAD

**Issue by ezgoodnight** [MiSTer-devel/NES_MiSTer#323]
Recent update has consistently frozen (black screen) after 4-4 in Super Mario Bros 2 Japan. I've tried two versions of the ROM, with no change. 

Reverting to 20220212.rbf fixes the issue for me. I have not tried 20220326.rbf yet but can if requested.

**Comment by SegaSnatcher** [comment]
Please post a save state if you can.

**Comment by ezgoodnight** [comment]
Yes, I was chatting with the discord about that as well. I would post a savestate if I could. SMB2J is fairly cruel.

**Comment by paulb-nl** [comment]
Should be fixed now with 88a5b54bfb3a90435c1114720fd6c89d4fbb0a58

**Comment by Vampier** [comment]
fix confirmed by Twitch streamer bigboiter- thanks paulb-nl!

**Comment by betsyheaven** [comment]
here's "Nes 22.07.25 88a5b54" with the fix working
https://youtu.be/ThWcUTnH4m4?t=1423

here's the game freezing after 4-4 on current public release "NES 22.07.12"
https://youtu.be/QWeoS0NX4do?t=2335

**Comment by thehughhefner** [comment]
This is fixed in the latest release. Issue can be closed

**Comment by Vampier** [comment]
this was indeed pushed to 'main' last weekend
