### ISSUE TITLE
super mario bros tetris nintendo world cup 3 in 1 not booting up

### ISSUE THREAD

**Issue by Alex-Catalin** [MiSTer-devel/NES_MiSTer#326]
Yesterday while playing on my NT Mini, I tried booting up the PAL cartridge 3 in 1 Super Mario Bros + Tetris + Nintendo World Cup and while the cart loaded, I was able to start only Tetris, the other 2 games would always reset to the cart's selection menu.

I then tried to run the same game via N8 Everdrive Pro on the NT Mini and I was unable to boot any rom variant. I then checked on the NESTER emulator and there the game starts and I am able to select and play any of the 3 included games.

Today, I tried the same rom files (there are 2 of them _"Super Mario Bros. + Tetris + Nintendo World Cup (Europe) (Rev A)"_ and _"Super Mario Bros. + Tetris + Nintendo World Cup (Europe)"_) on MiSTer and to my surprise, they are not booting up at all, I get a gray screen and that's it. I am on the latest version of the NES core, NES_20220712.rbf.

**Comment by Kitrinx** [comment]
I have tried this rom
Super Mario Bros + Tetris + Nintendo World Cup (Europe) and it boots fine on the nes core. Perhaps your header is incorrect.

**Comment by Alex-Catalin** [comment]
It's the rom versions that I have. I used another rom that I found on the net and that worked fine and it also worked on my Nt Mini with an Everdrive. I am closing this issue since it's not actually an issue :).
