### ISSUE TITLE
Family Circuit '91 (Japan) - hangs during the play

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/NES_MiSTer#329]
Hi,

During the play, the game hangs and after few minutes it comes back to the title screen.
You will find below a save state during the hang.
[Family Circuit '91 (Japan) (En)_1.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/9623946/Family.Circuit.91.Japan.En._1.zip)

Thanks !

**Comment by paulb-nl** [comment]
Can you explain how to reproduce? I can't get the game to hang.

**Comment by wwark** [comment]
I just play a Free practice after some time the game stops to respond like the save state I shared above.
With this save state are you able to play or it is not the case ? This save state is valuable to understand why we can't move or return to the menu.
Thanks !

**Comment by paulb-nl** [comment]
I have tried Free practice but the only thing that happens is that the fuel runs out and the car goes slower and stops but in that case I can still return to the menu by pressing start & select. 

Yes with your save state the game is frozen and start & select does nothing but I cannot reproduce it.

How long do you play until it hangs?

**Comment by wwark** [comment]
I played around 20 to 30 minutes before the hang appeared.
You will find below the information of my rom just in case.
Sha1sum : 89a79a601b8e900378035cb54248843eee24aafc  Family Circuit '91 (Japan) (En).nes
![image](https://user-images.githubusercontent.com/469461/203715073-23f51dc6-26c4-4494-b778-74cc05a3bee1.png)

**Comment by wwark** [comment]
New save state
[Family Circuit '91 (Japan) (En)_2.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/10081649/Family.Circuit.91.Japan.En._2.zip)

**Comment by paulb-nl** [comment]
20 mins! Well, no wonder I couldn't reproduce it.

I made a build with some changes for mapper 210 including the 2KB of RAM instead of the normal 8KB.
It would be good if you can test it.
[NES_map210_20221124.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/10084422/NES_map210_20221124.zip)

**Comment by wwark** [comment]
With this build I couldn't reproduce the hang.
Thanks a lot.
I will continue to test it.

**Comment by wwark** [comment]
Thank you for the PR. I close this issue

**Comment by paulb-nl** [comment]
Wow it has been almost 2 years since I first looked at this issue. Sorry it took so long.
