### ISSUE TITLE
Startropics can't register name

### ISSUE THREAD

**Issue by spikestabber** [MiSTer-devel/NES_MiSTer#33]
This happens no matter what ROM is used, haven't seen anyone report of it not working so I am wondering if it's just me. Emulators often had the problem with non hacked roms but even the newer musicfix ones do the same.

**Comment by greyrogue** [comment]
https://github.com/greyrogue/NES_MiSTer/commit/52ddd56efa110db3f86a1224242a54dcb7dfb9a2
Note this requires NES 2.0 headers with Submapper 1 specified.

**Comment by spikestabber** [comment]
Cheers, been playing ST with this fix, quick work! Thanks.

**Comment by James-F2** [comment]
Can this be closed?

**Comment by spikestabber** [comment]
Of course. Ta.

**Comment by James-F2** [comment]
Are you sure it has been fixed in the official release?
Seems to be still broken.
