### ISSUE TITLE
Dogbone controller won't work over SNAC

### ISSUE THREAD

**Issue by GoldenKain** [MiSTer-devel/NES_MiSTer#330]
None of my Dogbone controllers (HVC-102) work with my SNAC adapter. Any way you could fix this? My regular rectangle controllers work fine, but I would rather use a dogbone.

**Comment by paulb-nl** [comment]
I have a few Dogbone controllers (1x NES-039, 2x HVC-102) and they work without issues. 

Which SNAC adapter do you use? I have the one with the USB connector.

**Comment by GoldenKain** [comment]
I'm using the one with an HDMI port from MisterAddons. I don't know if that has anything to do with it, but my dogbones (which are from japan and have a shorter cord) are "modded" with an NES controller (as in a controller for the american system) cord so it's longer. I double and triple checked the pinout yesterday to be sure and they DO work on my NES and AV Famicom, so I'm pretty sure that shouldn't be an issue... I have another japanese dogbone controller that hasn't had it's cord changed that I can try later if anything 🤔

**Comment by GoldenKain** [comment]
I can't for the life of me find my stock dogbone controller... but I rechecked the cable's connections and everything and it should work fine and works perfectly on my NES and AV Famicom. I'll link pictures of the board.

![PXL_20221008_041424878](https://user-images.githubusercontent.com/44177820/194687738-2342facd-4529-4185-8c0b-baad043774a1.jpg)
![PXL_20221008_041127576](https://user-images.githubusercontent.com/44177820/194687742-20531b77-8059-479d-8c68-2d42a43311a5.jpg)
![PXL_20221008_040929629](https://user-images.githubusercontent.com/44177820/194687744-d64f2f43-4014-44b9-ad12-1fa06fcce1c7.jpg)

**Comment by Kitrinx** [comment]
You should discuss this with whomever makes your SNAC hardware, this is not an issue that can be addressed in the core. The core does not do any kind of interpretation of protocols and cannot modify the behavior of a specific controller.
