### ISSUE TITLE
Cat Ninden Teyandee game cannot be started from the first stage

### ISSUE THREAD

**Issue by MiguelTobon** [MiSTer-devel/NES_MiSTer#334]
**Problem:** when running the Cat Ninden Teyandee game on NES core in the latest version released, NES_20221002.rbf, (not sure about previous version) the game starts apparently and in the first stage when just moving some steps with the character selected, the game just freezes with the music continuing and a lot of graphic garbage is shown.

**Comment by Kitrinx** [comment]
This game has no problem running. Please check your rom for corruption and make sure the header is correct.

**Comment by MiguelTobon** [comment]
hey @Kitrinx you were right the rom is corrupted, I tried another one and I works, my bad on not trying out other versions. Thanks
