### ISSUE TITLE
SMB3: Floor jumping up during ending sequence

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/NES_MiSTer#335]
The floor randomly jumps up for one frame once in a while during the ending sequence:

https://youtu.be/Vd19pTCdZEk

Please disregard the dishwasher noises in the background. :P

**Comment by Kitrinx** [comment]
1) Does this happen on real hardware?
2) Do you have a savestate?

**Comment by AtomicShroom** [comment]
I've never seen this on real hardware.

Here's a savestate:

[Super Mario Bros. 3_1.ss.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/10255004/Super.Mario.Bros.3_1.ss.zip)

**Comment by TesterNes** [comment]
@AtomicShroom In the video you posted as real hardware at 14:17 the floor bounces aswel.
