### ISSUE TITLE
Core doesn't show any picture on my 4K TV half the time

### ISSUE THREAD

**Issue by the-importer** [MiSTer-devel/NES_MiSTer#34]
Hey there,

So I have my MiSTer hooked via HDMI on my Samsung 4K/UHD TV (UN55KU6290). Most of the time, this core will not show me any picture when loading any game, I'll only see the MiSTer interface when I hit the menu button. I'll hear a game play with the sound going through the HDMI, but no picture. It will however display via VGA on an old monitor that I've hooked via the IO board.

So ya, I get a blank image on my TV while the sound passes through but I do get the picture on my monitor. Sometime, after playing around with a bunch of different cores that work every time (SNES, Genesis, PC-Engine), it will eventually display on my TV , but that's on rare occasion.

I get a similar with the Master System core and more often with the GameBoy core. Any idea of what's going on and how to fix it?

Thank you

**Comment by sorgelig** [comment]
don't spam!
