### ISSUE TITLE
Famista ‘94 - ‘92 graphics corruption

### ISSUE THREAD

**Issue by deepthaw** [MiSTer-devel/NES_MiSTer#342]
From a cold reboot, launching Famista ‘94 through ‘92 results in corrupted graphics. Famista ‘91 launches fine, and then the others work fine after launching it once. Reloading the core causes them to start with corrupted graphics again until I load ‘91.

(The video shows it happening with MikeS’s YC fork of the NES core but I can verify it happens with the standard version as well.)

https://youtube.com/shorts/hqVVXshVidA?feature=share

This was originally noticed by CGQuarterly on Twitter.

https://twitter.com/cgquarterly/status/1621333563978440704

**Comment by Kitrinx** [comment]
What happens on a real system?

**Comment by paulb-nl** [comment]
As usual: https://twitter.com/CGQuarterly/status/1621352646392311808

**Comment by Kitrinx** [comment]
I was going to comment that my roms worked fine as well. Bad headers strike again.

**Comment by SegaSnatcher** [comment]
> As usual: https://twitter.com/CGQuarterly/status/1621352646392311808

Yep, typical bad header issue.  Dealing with bad headers so much through the years made it easy to spot lol.
