### ISSUE TITLE
Castlevania III graphical corruption

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/NES_MiSTer#35]
Core: 19.01.21

If you let the intro play, the story text has graphics in some portion (such as the whip) that are garbled until they're on the screen for a little bit. When you start a game and pick up the whip power-up, it garbles the whole screen for a second. This only seems to happen if you let the intro play until you see the garbled intro graphics.

**Comment by James-F2** [comment]
Still corrupted with190307 build. 
When watching the intro I can see text turning into graphics and vice versa.

**Comment by James-F2** [comment]
This is fixed in the up coming release.

I can still see a single corrupt scanline between the UI and Gameplay screen, during gameplay.

**Comment by paulb-nl** [comment]
You have eyes like an eagle James. It is hard to notice because the colors are the same as the background. It's fixed now too.

**Comment by James-F2** [comment]
Amazingly fast.
Well done Paul !

**Comment by James-F2** [comment]
Fixed in 2019.04.09, can be closed.

**Comment by James-F2** [comment]
@paulb-nl 
After Rysha's huge PR (17th April), the GUI glitchy scanline is back.
