### ISSUE TITLE
Donkey Kong (arcade/vertical orientation) not booting

### ISSUE THREAD

**Issue by protogem2** [MiSTer-devel/NES_MiSTer#351]
Sumez's arcade hack of Donkey Kong for vertical resolution/tate + arcade additions does not boot in the core. It uses mapper 0 (NROM) and is confirmed to work on real hardware (as well as Mesen emulator with internal game database disabled).

I tried converting the iNES header to 2.0 and tweaking various options but it did not help.

**Comment by protogem2** [comment]
https://github.com/MiSTer-devel/NES_MiSTer/issues/217

This issue has already been resolved, apologies. Please close this issue.

**Comment by Toryalai1** [comment]
You can close it yourself. You created it
