### ISSUE TITLE
Y/C output severly downgraded since merging MikeS cores

### ISSUE THREAD

**Issue by mattd121** [MiSTer-devel/NES_MiSTer#353]
The NES core has severely downgraded performance with the integrated Y/C output through a **passive** MikeS-design adapter compared to the separate Y/C cores. Integrated Y/C shows extreme dot crawl and flickering of lines like the black outlines of the Super Mario Bros hills. I have tested with the last separate Y/C MikeS cores and it runs great with those. Something happened since the merging of the cores that downgraded its performance. I do not have an **active** MikeS design adapter to test with for comparison.

**Comment by sorgelig** [comment]
@MikeS11

**Comment by mattd121** [comment]
Thank you, that worked. My OG unmodded front loader does not seem to have the dot crawl I was seeing in the core default (when stationary, not scrolling) but I know there are many revisions to the hardware and mine is one of many.

**Comment by paulb-nl** [comment]
I see in the yc.txt file that the phase value for the NES is the same as the SNES. Normally this would be correct but the NES core has been changed to not have the skipped dot every other frame that original hardware has specifically to improve composite dot crawl.

The SNES core still has the skipped dot.

IMO now that we have composite out the skipped dot removal should be optional.

**Comment by MikeS11** [comment]
Yeah I did have a look at changing that as well and through testing I didn't see too much of a difference. But I wasn't focusing on dot crawl at the time. Maybe I'll revisit.
