### ISSUE TITLE
Konami VRC2/VRC4 not working properly since last core update

### ISSUE THREAD

**Issue by mambrino** [MiSTer-devel/NES_MiSTer#356]
Hi,

The game "Bio Miracle Bokutte Upa" crashes a few seconds after starting to play. In the previous release (20221002) it works perfectly.

**Comment by Thelypody** [comment]
There are two distinct versions of this game. Are you talking about the original Disk System release (.fds) or a later cartridge rerelease (.nes)?

**Comment by mambrino** [comment]
nes cartridge, sorry. Disk works ok

**Comment by Thelypody** [comment]
I just tried the cartridge version and it seems to run fine on my end. Make sure that your rom has proper NES 2.0 header. Working rom has a CRC32 checksum of CC4C8E9C.
If you have a hex editor on your hand, you can manually apply the proper header to your rom by replacing (presuming that your rom already has some kind of header) the first line of hex values with this:
4E 45 53 1A 08 10 90 18 10 00 00 00 00 00 00 01

**Comment by mambrino** [comment]
Indeed, with that rom it works fine. I was confused by the fact that the rom I had worked on previous version of the core and not on the last one.

Thanks and apology the inconvenience.

**Comment by mambrino** [comment]
I have to reopen the issue, since I have played Bio Miracle Bokutte Upa again (Japan 2.0 header - CRC CC4C8E9C), and this time has completely crashed at second level.

It also happens with Gradius 2 (Japan 2.0 header - CRC AC05FFF5). In this case freezes as soon as the game start.

I have checked again with the previous version of the core (20221002) and this doesn't happen, in fact both games work perfectly.

I would appreciate if someone can test on their MiSTer.

Thanks!

**Comment by mambrino** [comment]
Akumajō Special: Boku Dracula-kun (Japan 2.0 header - CRC c3945386) also fails, in my case it crashed on the second level, it also works perfectly with the previous core verison

**Comment by AtomicShroom** [comment]
I tried both Gradius II and Bio Miracle Bokutte Upa on my end and I have not had any problems with them.

**Comment by caiosilva1993** [comment]
> Akumajō Special: Boku Dracula-kun (Japan 2.0 header - CRC c3945386) also fails, in my case it crashed on the second level, it also works perfectly with the previous core verison

Same problem here.

> I have to reopen the issue, since I have played Bio Miracle Bokutte Upa again (Japan 2.0 header - CRC CC4C8E9C), and this time has completely crashed at second level.
> 
> It also happens with Gradius 2 (Japan 2.0 header - CRC AC05FFF5). In this case freezes as soon as the game start.
> 
> I have checked again with the previous version of the core (20221002) and this doesn't happen, in fact both games work perfectly.
> 
> I would appreciate if someone can test on their MiSTer.
> 
> Thanks!

Same problem here.

**Comment by BigDanG** [comment]
I'm able to recreate this as well, though I first noticed it with the Japanese ROMs for Contra and the TMNT games. The key thing for me is a warm-up period. I'm using a Retrocastle aluminum enclosure with passive cooling.

Here are my steps to reproduce:

1. Run the unit to warm it up. 
    - For me I run the SDRAM test until it fails its first 150 MHz test, usually around 20 mins. 
2. Play a VRC2 or VRC4 game in the NES_20230223 core.
    - I used Contra (Japan), CRC32: 08789A28
3. Observe the crash in game.
    - This happens within minutes, between the title screen an the exploding bridge.
4. Play the same game in the NES_20221002 core. Observe the crash doesn't occur.
    - I can reach the first infiltration screen without issue.
6. Return the NES_20230223 core, play the same game and observe a crash occurs.
7. Perform a cold boot, return to the NES_20230223 core , play the game and observe a crash.

Because this crash requires a warm-up period to manifest, and re-manifests after a cold boot, I believe the thermals are affecting something like timing characteristics for the VRC2/VRC4 implementation in the NES_20230223 release.

Please let me know if there's anything else you'd like me to try or need any more info from me.

**Comment by mambrino** [comment]
Thanks for the tests, very useful to confirm that it is a problem with mapper VR2/VR4 games (I change the title of the issue).
I have tried other games using this mapper and I also have problems with:

- Ganbare Goemon Gaiden - Kieta Ougon Kiseru (J) [CRC32: B51CD53E]
- Ganbare Goemon Gaiden 2 - Tenka no Zaihou (J) [CRC32: 3ECBD020]
- Ganbare Pennat Race (J) [CRC32: 40743632]
- TwinBee 3 - Poko Poko Daimaou (J) [CRC32: 077876C0]
- Wai Wai World (J) [CRC32: 3095F6D1]
- Wai Wai World 2 - SOS!! Paseri Jou (J) [CRC32: 083B1E00]

In the specific case of my mister, you don't need to wait for it to warm up, it already gives problems with that mapper since I turn it on. Maybe it's because memtest gives me errors from 143mhz, but I don't understand it, because I remember that the core is designed to work at approx. 86mhz.

**Comment by rls03c** [comment]
I'm also encountering this on Gradius II and the JP version of Contra. I can usually make some progress in the latter before it freezes.

**Comment by ClassicGamerRG** [comment]
I played Contra (J).nes (CRC32 8A96A3C4) rom with the last core version without any issue, even after a memtest warm up.

**Comment by BigDanG** [comment]
I couldn't reproduce the issue with release 231204 on my unit either.

**Comment by rls03c** [comment]
I played all the way through Gradius II and most of the way through Japanese Contra and everything looked fine on my end.
