### ISSUE TITLE
[Suggestion] Add Undo Save/Load on the menu

### ISSUE THREAD

**Issue by capitaineflam25** [MiSTer-devel/NES_MiSTer#358]
Overwriting the current save state can sometimes be very frustrating.
A file based undo feature could help solving that, like the one on RetroArch.

Assume you're playing SMB and current save slot is 1.

Before saving, rename SMB_1.ss to SMB_1_prev.ss
If "**Undo Save State**" is pressed, rename SMB_1_prev.ss to SMB_1.ss

Before restoring a state, save current state to SMB_1_undo.ss
If "**Undo Load State**" is pressed, load SMB_1_undo.ss

**Comment by Toryalai1** [comment]
This is a framework request and not an issue for the NES core. I suggest closing this and open it in main.

**Comment by capitaineflam25** [comment]
OK thanks.
I didn't know save mecanism was on framework side.
