### ISSUE TITLE
Don Doko Don 2 (Japan) graphical corruption

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/NES_MiSTer#36]
Core:  190121

There's graphical corruption in the game. The most noticeable is the title screen. in-game seems to be more minor.

**Comment by greyrogue** [comment]
I believe this is an issue with your header.  Don Doko Don 2 is a mapper 48 [bytes 6/7 = 0x00/0x30] cart (Taito TC0690), not mapper 33 [bytes 6/7 = 0x01/0x20] (Taito TC0190).  Make sure you set your header correctly when you dumped the game.
https://wiki.nesdev.com/w/index.php/INES_Mapper_048

**Comment by cr4zymanz0r** [comment]
> 
> 
> I believe this is an issue with your header. Don Doko Don 2 is a mapper 48 [bytes 6/7 = 0x00/0x30] cart (Taito TC0690), not mapper 33 [bytes 6/7 = 0x01/0x20] (Taito TC0190). Make sure you set your header correctly when you dumped the game.
> https://wiki.nesdev.com/w/index.php/INES_Mapper_048

That appears to have been the issue. Once it was set to the correct mapper in the ROM header then it appears to work fine (no obvious signs of graphical corruption). I assumed it would've had issues in PC emulators as well with it set to the wrong mapper.
