### ISSUE TITLE
Feature request: SNAC/SNAX Vaus controller support (NES, or Famicom version 1 and 2)

### ISSUE THREAD

**Issue by protogem2** [MiSTer-devel/NES_MiSTer#362]
The Vaus controllers would be a nice addition to use in the core for Arkanoid 1 and 2, especially 2 as the second version of the Famicom Vaus controller supports daisy chaining a second Vaus for the 2 player mode in Arkanoid 2.

As near as I can tell there would be enough pins on SNAC/SNAX to implement at least one controller of either the NES or Famicom type. An option to remap the memory from the NES/Famicom version to the other for software compatibility with any Vaus model would be a nice idea as well.

I am unsure if there are enough pins to accommodate the daisy chained Vaus controllers supported by the second Famicom Vaus but it seems like there should be (the second controller is remapped to other pins on the 15 pin port)

For the Famicom models there dont seem to be any adapters on the market for SNAC supporting 15 pin accessories (lack of support for all pins Id guess) but an adapter could be made I'd think.

**Comment by Kitrinx** [comment]
It appears to use a total of 4 pins, and should already be supported with a correct adapter. Ask your local hardware seller for an adapter for this controller. No modifications can/will be made to the core for this.

**Comment by protogem2** [comment]
Arkanoid 2's Vaus variant for player 2 passthrough seems to simply map player 1 controls to player 2 pins for the second controller, which could be routed to the second NES controller port for SNAC it seems.

However, the addresses used by player 1 and player 2 for 15 pin Famicom controllers (including Vaus controllers) do not seem to correspond to those used by the normal controller ports. Will the core be able to accurately translate this to the game by simply using an adapter?
