### ISSUE TITLE
Random issues when loading new games (after other games were previously loaded)

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/NES_MiSTer#37]
Core: 190121

Some games exhibit strange behavior if loaded after other games were loaded. It's almost as if there still some data left in memory/registers/whatever that interferes with the new game. Here's some examples:

Akumajo Densetsu (Japan) (encountered frequently)
Game only loads a single screen of garbage graphical data then never proceeds.

Batman: Return of the Joker, hung music note (encountered once)
Immediately once the game is loaded there is a constant tone that plays throughout the game.

**Comment by James-F2** [comment]
Fixed in2019.04.09, can be closed.
