### ISSUE TITLE
Problem with SNAC in 20231204 ver.

### ISSUE THREAD

**Issue by Death-Devil-94** [MiSTer-devel/NES_MiSTer#372]
Core version 20231204 having issue with the some japanese titles via SNAC adapter. Pressing START on controller works as SELECT button. D-Pad UP is Start. Game titles was spotted: Antarctic Adventure, Contra. US version of game nothing changed.
In unstable version 20230728 works perfect with SNAC. 
Tested on 8bitdo N30 2.4g

**Comment by sorgelig** [comment]
I don't see any changes related to SNAC during that period.

**Comment by Death-Devil-94** [comment]
uploaded [Video](https://www.youtube.com/watch?v=zgx9vlEUkb8) how it works for me

**Comment by sorgelig** [comment]
try this build:
[NES.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/13644904/NES.zip)

**Comment by Death-Devil-94** [comment]
Antarctic Adventure (J) works, Contra (J) still having the same issue

**Comment by paulb-nl** [comment]
At the end of your video it shows that you are not using the SNAC level translator board so your controller adapter is receiving 3.3 volt instead of required 5 volt.  This can cause issues.

**Comment by Death-Devil-94** [comment]
> At the end of your video it shows that you are not using the SNAC level translator board so your controller adapter is receiving 3.3 volt instead of required 5 volt. This can cause issues.

Then how is it that in the latest 'unstable' version of the core everything works as it should be, but it is in the latest 'stable' version of the core that this problem appears only in the Japanese versions of games? The American versions of the games are not affected by this

**Comment by sorgelig** [comment]
I think it's edge case. If proper level translator isn't used, then signals from MiSTer to controller will be delayed, and depending on several factors it may read previous/next button.

**Comment by Death-Devil-94** [comment]
Closing this issue, working now in 20240408 core build
