### ISSUE TITLE
FDS: Bishoujo Kachinuki Renju - Gomoku Narabe (Japan) (Unl) - Error 20

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/NES_MiSTer#376]
NES core: 20231204, Main: 20240110
Bishoujo Kachinuki Renju - Gomoku Narabe (Japan) (Unl).fds
CRC32: FF06EB11

This unlicensed board game for the Disk System instantly triggers FDS Error 20 on startup.
![20240312_011250-Bishoujo Kachinuki Renju - Gomoku Narabe (Japan) (Unl)](https://github.com/MiSTer-devel/NES_MiSTer/assets/70150033/d06294da-0149-40eb-8003-eb3d92e266e8)
Disk image boots fine in Mesen 2 emulator.

**Comment by paulb-nl** [comment]
Pull request #387 has a fix for this. The next release will have an option to set the disk speed to original speed. This game needs that.

**Comment by Thelypody** [comment]
The game works now with FDS speed set to Original. Tonkachi Mario works as well, Thank you!
