### ISSUE TITLE
FDS audio is inaccurate

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/NES_MiSTer#38]
Core: 190121

The FDS audio is inaccurate/wrong. One noteable example is in Almana no Kiseki. For lack of a better word, some of the music "flutters". That doesn't happen on original hardware. Here's a video of what it should sound like: [https://www.youtube.com/watch?v=usCCn_dnl4I](url)
Compare the intro and 1st level themes in the video to how they sound in the FPGA core.

**Comment by Kitrinx** [comment]
This issue should be resolved now

**Comment by cr4zymanz0r** [comment]
It's MUCH better now, to the point that I'm not hearing anything I'm 100% sure of just going off of memory. I'm going to do a side by side listen with real hardware when I get some time to make sure before closing the issue.

**Comment by cr4zymanz0r** [comment]
Got to dig in with testing on the latest core (as of today) and it sounds great. Closing issue
