### ISSUE TITLE
FDS: Tonkachi Editor does not function

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/NES_MiSTer#385]
NES core: 20240408, Main: 20240505

Tonkachi Editor is an unlicensed disk released for the Family Computer Disk System in 1987. The primary function of the program is a hex editor, but the disk also gives you an opportunity to insert a copy of Super Mario Bros. (1) for FDS to overwrite it with prepackaged new content, creating a game version commonly known as Tonkachi Mario, considered to be one of the earliest romhacks of the game.

I've tried to replicate the process of creating a Tonkachi Mario disk in an authentic way. For this purpose I've merged two disk images:
Tonkachi Editor (Japan) (Unl).fds (CRC32: BEA8B9A2)
Super Mario Bros. (Japan).fds (CRC32: E0890CF2)
The resulting new file (CRC32: 35702D8D) has the editor program on side A and the game on side B and both sides properly boot separately when swapping disk sides in the core on console startup.

Launching the side A prompts you to eject the Tonkachi Editor disk.
![20240721_161815-Tonkachi Editor + Super Mario Bros  (Japan) (Unl)](https://github.com/user-attachments/assets/ae5c51cf-1687-4700-b2d9-b3063648303e)
Holding the FDS button (or releasing it to swap sides to Super Mario Bros.) shows us two options. The first is a hex editor, the second is a Tonkachi Mario creation tool.
![20240721_161835-Tonkachi Editor + Super Mario Bros  (Japan) (Unl)](https://github.com/user-attachments/assets/3d65528d-ee3f-4625-973c-ccb4b4120e98)
Selecting the second option starts an unfortunately lengthy text scroll accompanied by music. You are supposed to insert the game disk while it is going.
![20240721_161916-Tonkachi Editor + Super Mario Bros  (Japan) (Unl)](https://github.com/user-attachments/assets/74a5b791-924e-4641-bcff-6749b55d9172)
After the text scroll a brown screen appears, indicating supposed activity. Unfortunately, at this point the program freezes. Rotating disk sides with the FDS button asks us to insert disk again, but nothing happens regardless.
![20240721_131043-Tonkachi Editor + Super Mario Bros  (Japan) (Unl)](https://github.com/user-attachments/assets/d81ac569-3b7c-4f4d-a796-62f8664ef369)
I've found a video demonstration of Tonkachi Editor on YouTube, which shows that at this point the program is supposed to take a few seconds to overwrite the disk and then show a blue screen saying "END".
https://youtu.be/kqmQ6ljEghA?si=Xp5Q-JPJVMvzsmFo&t=334
On MiSTer the brown screen shows no signs of disk activity and stays permanently on the brown screen. No save file is created for the disk image.
Trying to access the hex editor from the main menu shows similar results, with the program constantly asking to insert a game disk.

**Comment by paulb-nl** [comment]
This is fixed with #387. The hex editor works and Tonkachi Mario also works.
