### ISSUE TITLE
Pac-Man CE Hack Stopped Working After Core Update

### ISSUE THREAD

**Issue by SWCDX2** [MiSTer-devel/NES_MiSTer#389]
Hi, the following (hacked) NES ROM stopped working after the last core update:

Pac-Man CE (Eyes + Start Fix v1.0) by SuperEgz.nes

https://www.romhacking.net/hacks/7551/

I don't know if this info helps:

* Format: iNES
* External Header: Yes
* Mapper #: 19 ($13)
* Mapper name: Namcot_106

Is this a hack issue, or a core issue?

Thank you.

**Comment by paulb-nl** [comment]
Try to change the NES header to NES 2.0 with 8KB NVRAM.

**Comment by SWCDX2** [comment]
OK I think I tried what you suggested. I used 'iNES Header Editor' (nes2edit.exe) to set CHR RAM to 8K. But the problem remains.

Here's a screenshot:

https://imgur.com/a/mGYkDVU

**Comment by paulb-nl** [comment]
It is the PRG RAM one that you will need to set to 8KB. The one with battery above it

**Comment by SWCDX2** [comment]
It works!

Thank you very much.
