### ISSUE TITLE
HDMI Color palette to emulator 

### ISSUE THREAD

**Issue by TheBoxGame** [MiSTer-devel/NES_MiSTer#395]
ok I'll tell you what I mean nes emulators and the original nes console has 54 colors and hdmi with famiclon can have more than 54
because I started the game ninja gaiden 3 on my famiclon via hdmi on a new tv and the sky is purple and in the game jackie chan the water is light blue in stage 3 and when I used the color of the purple sky from the game ninja gaiden 3 I noticed that in the game jackie chan in stage 3 the water is also purple and not light blue does hdmi support more colors than 54?
![IMG_20241001_172413](https://github.com/user-attachments/assets/350f3ac6-c9be-46be-8d18-f92f06974cfe)
![render_adj_avfamicom_misterpc10-1024x735](https://github.com/user-attachments/assets/3754311e-9cde-4ffb-9fd2-164540a28fb7)
![Screenshot_2024-10-19-17-49-12-293_com explusalpha NesEmu](https://github.com/user-attachments/assets/16d733d9-d486-4e0f-bf44-7e28bff21e8a)

**Comment by TheBoxGame** [comment]
> ok, powiem ci co mam na myśli. Emulatory NES i oryginalna konsola NES mają 54 kolory, a HDMI z Famiclon może mieć więcej niż 54. Ponieważ uruchomiłem grę Ninja Gaiden 3 na moim Famiclonie przez HDMI na nowym telewizorze i niebo jest fioletowe, a w grze Jackie Chan woda jest jasnoniebieska w etapie 3. Kiedy użyłem koloru fioletowego nieba z gry Ninja Gaiden 3, zauważyłem, że w grze Jackie Chan w etapie 3 woda jest również fioletowa, a nie jasnoniebieska. Czy HDMI obsługuje więcej kolorów niż 54? ![OBRAZ_20241001_172413](https://private-user-images.githubusercontent.com/109180532/378180357-350f3ac6-c9be-46be-8d18-f92f06974cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjMwMTEsIm5iZiI6MTcyOTQyMjcxMSwicGF0aCI6Ii8xMDkxODA1MzIvMzc4MTgwMzU3LTM1MGYzYWM2LWM5YmUtNDZiZS04ZDE4LWY5MmYwNjk3NGNmZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMTExNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTlhN2I1NDQ1ZjY4ZDNkY2E0YWYwYTgxYzliYjRhODllM2MwNTA2YmY2OGIzNTQ0MDQxODY0YjBiMjhiN2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.09Xl4Y7oXH00zup7rNtUY3RKslwJzVP-KXrOv2NvEUs) ![dostosowanie renderowania avfamicom misterpc10-1024x735](https://private-user-images.githubusercontent.com/109180532/378180468-3754311e-9cde-4ffb-9fd2-164540a28fb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjMwMTEsIm5iZiI6MTcyOTQyMjcxMSwicGF0aCI6Ii8xMDkxODA1MzIvMzc4MTgwNDY4LTM3NTQzMTFlLTljZGUtNGZmYi05ZmQyLTE2NDU0MGEyOGZiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMTExNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWYyNGUxMGE2NTQ5MmZjOGI1NjVjZDQ3MGE1MzRkNTZhMTlmMGM4YzJjMjU0N2IxYWQ3NDI1Zjc1NWMwYjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5JNf-ZjBVOcITdxWxAjz17M07bX844H-w-6Zm5zPDzY) ![Zrzut ekranu_2024-10-19-17-49-12-293_com explusalpha NesEmu](https://private-user-images.githubusercontent.com/109180532/378180470-16d733d9-d486-4e0f-bf44-7e28bff21e8a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjMwMTEsIm5iZiI6MTcyOTQyMjcxMSwicGF0aCI6Ii8xMDkxODA1MzIvMzc4MTgwNDcwLTE2ZDczM2Q5LWQ0ODYtNGUwZi1iZjQ0LTdlMjhiZmYyMWU4YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMTExNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2NiMGE5M2VlNzQyZWEyNjkyMzQ3NjU0NDA3OTdmNTVmYTllNzlhOGZjYjlmNzMyYThjYWFjNDJmMmNlYzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KCp_yzpP_KThA11fMy99OPutWTm4Hgz49H6SmYCVNG0)

![Screenshot_2024-10-19-17-48-45-991_com explusalpha NesEmu](https://github.com/user-attachments/assets/7d29604f-e256-4027-9f8e-6b1338259175)

**Comment by Kitrinx** [comment]
The NES palette is technically 64 colors. The official NES and Famicoms use 54 of these colors and the rest are various shades of black (true black and also a very dark grey type black). These colors can't be populated in standard palettes because games are known to arbitrarily use various indexes of these other black colors, so if they are populated, it will appear as a colored artifact on the screen rather than black. In the case of games that are intended to use more colors, you simply have to use a correct palette that has those colors properly populated. The VS palettes for instance use all 64 colors.

Regarding blue vs purple, this is an age old war which boils down to: NES is composite and some of it's blue values are electrically invalid for the composite spec. How the television chooses to deal with these out of range voltages determines whether the color is shown as periwinkle, purple, or blue.

**Comment by TheBoxGame** [comment]
ok thanks

**Comment by Kitrinx** [comment]
Since this seems addressed or not related to the core, i'm closing the issue
