### ISSUE TITLE
Region Unlock Famiclon

### ISSUE THREAD

**Issue by TheBoxGame** [MiSTer-devel/NES_MiSTer#397]
hello I have a question does anyone know about famiclons if so I would like to ask if my famiclon has a regional lock because when I run the f1 sensation game in the European version from the legendary nes 509-in-1 compilation it plays too fast is there a way to bypass the regional lock

**Comment by Kitrinx** [comment]
Are you playing it with the console set to PAL?

**Comment by Kitrinx** [comment]
I don't think I understand what you are asking. The only "console lock" on NES games was the CIC chip which isn't relevant to mister. If it's a european release, it's timings are likely made for PAL consoles, so set the console to PAL to get the correct speed. You can try Dendy mode to get the special clone vblank timings for some of the russian type bootleg games. That's all there is as far as I know.

**Comment by birdybro** [comment]
That's not a regional lock. That's just the game playing at different speed.

This is the place to report issues with the NES core for MiSTer FPGA. It doesn't sound like you are having an issue with this core. I would suggest asking these questions in a retro gaming forum or a retro gaming chat.

**Comment by Kitrinx** [comment]
Since this seems unrelated to this core, I am closing the issue.
