### ISSUE TITLE
Youkai Club (J)does not start properly

### ISSUE THREAD

**Issue by gatarib** [MiSTer-devel/NES_MiSTer#399]

**Comment by gatarib** [comment]
![youkai](https://github.com/user-attachments/assets/773541b5-2bc2-478f-8b2d-54d3c80060ee)

**Comment by paulb-nl** [comment]
Youkai Club should be mapper 140. Change the header.

**Comment by gatarib** [comment]
> Youkai Club should be mapper 140. Change the header.

Resolved, thank you.
