### ISSUE TITLE
Default button mappings are backwards

### ISSUE THREAD

**Issue by Kitrinx** [MiSTer-devel/NES_MiSTer#4]
NES controllers are traditionally B on the left, A on the right.
Currently the primary "OK" button is mapping to A, and the "Cancel/back" button is mapping to B.

This can be remapped to be positioned correctly, but then the OSD functions are reversed.

**Comment by sorgelig** [comment]
It's a system-wide mapping unrelated to NES: first button->OK, second button->Cancel
