### ISSUE TITLE
Missing pixel columm when hide overscan is off using scandoubled vga output.

### ISSUE THREAD

**Issue by elexor** [MiSTer-devel/NES_MiSTer#43]
https://youtu.be/hEU5duLVxqM

**Comment by sorgelig** [comment]
upload that test ROM so i (and others) will be able to test as well.

**Comment by elexor** [comment]
Hi sorgelig I used the 240p test suite you should be-able to see it with any rom it's really easy to see when switching over scan on and off.

**Comment by James-F2** [comment]
I see the same missing pixel column with "Scandoubler FX" with HDMI.

**Comment by sorgelig** [comment]
ok. i can reproduce it.

**Comment by sorgelig** [comment]
should be fixed already

**Comment by elexor** [comment]
Fixed. thanks Sorgelig.
