### ISSUE TITLE
Asterix (Europe exclusive) heavy graphical corruption

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/NES_MiSTer#52]
Asterix has heavy graphical corruption once you get into stage 1. It is highly likely this is because the core doesn't seem to have any options to simulate a PAL NES. The game also has graphical corruption on a real NTSC NES.

**Comment by sorgelig** [comment]
So, this is not an issue. It's from unsupported region.
Close till PAL support will be added.
