### ISSUE TITLE
Sexy Invaders (FDS): Disk loading infinite loop after the title screen

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/NES_MiSTer#56]
Core 190409
Game loads to title screen fine, but it keeps loading the disk to side B over and over after you hit start. Change the disk swap to manual (button) doesn't fix the issue either.

**Comment by cr4zymanz0r** [comment]
As of the latest commits at the time of this post, the game will now load when using manual disk loading. Unsure if this should be considered resolved, or if the expectation is that every game should work with auto disk swapping. @Kitrinx @greyrogue

**Comment by Kitrinx** [comment]
This is now resolved by using manual mode FDS swapping.
