### ISSUE TITLE
VRC7 audio (Lagrange Point) is inaccurate

### ISSUE THREAD

**Issue by cr4zymanz0r** [MiSTer-devel/NES_MiSTer#58]
Core 190409
In the intro music right after you name your character, roughly 15 seconds into the music there is a popping noise that is not present (or at the very least, extremely dampened) on the real cart's audio.
Here's a recording of it on original hardware vs MiSTer: [https://drive.google.com/file/d/1Ds94BdIA5Hy7uLJuRPnCht6fbG2fJ9ck/view?usp=sharing](https://drive.google.com/file/d/1Ds94BdIA5Hy7uLJuRPnCht6fbG2fJ9ck/view?usp=sharing)

I'm not sure if this if just needs a low or high pass filter, or if there's more to it. Also, I'm unsure if the VRC7 volume is too low or not. I had to amplify it quite a bit to get it closer to the recording of the volume from the AV Famicom (but that could just be how the AV Famicom mixes cart expansion audio).

**Comment by James-F2** [comment]
Now MiSTer sounds as close to the real cart + original famicom without lowpass filter.
The AV Famicom is not a good reference since it's not balanced and all external audio cartridged were made for the original red famicom.

This can be closed.

**Comment by cr4zymanz0r** [comment]
Audio sounds correct now. Maybe still needs a high and/or low pass filter in the future, but the tones generated sound correct now.
