### ISSUE TITLE
Battletoads & Double Dragon - Mapper AxROM glitchy pixels

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/NES_MiSTer#60]
https://wiki.nesdev.com/w/index.php/AxROM

Can be seen in the top row of pixels in Battletoads or Battletoads & Double Dragon in the intro demos.
Both these cartridges use AOROM which according to the link above has some "bus conflicts".

No visible pixel glitches in Mesen emulator with these games.
I don't know if that happens on real hardware with real cartridge.
I have Everdrive N8 but it has FPGA emulated mappers too, so it's not a good reference.

**Comment by paulb-nl** [comment]
Those glitches on the top line are sprites which according to the wiki should never show on line 0. Does it happen with the Everdrive on a NES?

**Comment by James-F2** [comment]
Does not happen on original console + Everdrive N8.
Also, the line 0 rysha pr lately did not fix the issue.

**Comment by paulb-nl** [comment]
I don't see any glitches at the top line anymore with the line 0 fix.

**Comment by James-F2** [comment]
NTSC rom.

![20190625_114245](https://user-images.githubusercontent.com/31185814/60083557-9b40ea00-973e-11e9-8b68-58f9a84e1fe7.jpg)
![20190625_114311](https://user-images.githubusercontent.com/31185814/60083556-9b40ea00-973e-11e9-84f4-daf41d764dbb.jpg)

**Comment by paulb-nl** [comment]
Ok I only looked at Battletoads instead of Battletoads and Double Dragon. Those glitches are on line 19. Both games disable rendering until the line before the glitches.

I found the issue was that the core was always writing to secondary OAM even when rendering was disabled so with that fixed no glitches now in both games even with the line 0 sprite disable removed. 

Sprite evaluation really needs a rewrite because it is not very accurate.

**Comment by James-F2** [comment]
> I found the issue was that the core was always writing to secondary OAM even when rendering was disabled so with that fixed no glitches now in both games even with the line 0 sprite disable removed. 
> Sprite evaluation really needs a rewrite because it is not very accurate.

@Kitrinx has said on discord that she's rewritten some parts of the PPU related to OAM.
I'm almost sure she knows what is the problem there.

**Comment by James-F2** [comment]
Amazing work Paul.
I'm closing this.
