### ISSUE TITLE
Sdram needed?

### ISSUE THREAD

**Issue by Jeebs14** [MiSTer-devel/NES_MiSTer#7]
Is it at all possible to have the games utilize the DDR instead of a required Sdram add on? I thought it was strange seeing core of like Genesis and PCE using the DDR and the NES doesn't. Just curious.

**Comment by sorgelig** [comment]
Genesis and PCE have VRAM in BRAM for graphics and large RAM also in BRAM. So, amount of delay added by high latency DDR used for ROM is not noticeable and doesn't break the macro timings.
NES have only small amount or RAM, so it utilizes ROM for code and video and latency of DDR affects the work very much.
