### ISSUE TITLE
Tengen Atari Hard Driving prototype ingame graphics garbled.

### ISSUE THREAD

**Issue by suverman** [MiSTer-devel/NES_MiSTer#74]
http://www.lostlevels.org/hard-drivin/

This game never got published officially but looks creative programming running a 3d like game like Hard Drivin on NES.

Emulators even Mesen have the road tearing 
![image](https://user-images.githubusercontent.com/42350878/57965777-37204e80-7966-11e9-8aac-aea96616404a.png)

OG hardware is not supposed to have it.

MiSTer NES core has garbled graphics - only dashboard looks ok.

According to discussions here it looks like mapper 64  / 158, both of which are implemented - the link below solves the wiring needed to be done to make the repro cart, maybe this will help to get the game running on MiSTer as well?:
http://forums.nesdev.com/viewtopic.php?p=125092&fbclid=IwAR17QkVRCSWshpsh1qu4LgceOI4ls_98a-pkUh9r4BEjJvkGonpy0JVaGdM#p125092

Thanks a ton for the great core.

**Comment by Kitrinx** [comment]
This should be resolved.

**Comment by suverman** [comment]
Thanks!!!! It is!
