### ISSUE TITLE
Captain Saver (Japan) Background tiles corrupted in stages

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/NES_MiSTer#78]
Select any stage and you will see corrupted tiles that are not there on console. Note that the US version, Power Blade 2 runs as intended, however that version uses MMC3 while this one uses Mapper 033, described in

https://wiki.nesdev.com/w/index.php/Talk:INES_Mapper_033

EDIT: Also note that Bubble Bobble 2 (Japan) also breaks on Round 8. There are some logs in the background that should be scrolling from left to right, but they don't appear to scroll on MiSTer currently. I bring this up in the same issue because this wiki entry leads me to believe the 2 bugs are related

**Comment by greyrogue** [comment]
Both Captain Saver and Bubble Bobble 2 are mapper 48 games, not mapper 33.  Make sure you test with the correct headers.

https://wiki.nesdev.com/w/index.php/INES_Mapper_048

**Comment by MP2E** [comment]
You're right! My roms have the wrong headers. However, when I change the mapper to 48 using Nintendulator's iNES header edit feature, it produces a ROM that simply black screens on the MiSTer. Oddly, a few emulators I tried still loaded it.

I then got a fresh ROM and followed your instructions on the Classic Gaming Discord to edit my headers with a hex editor, but that still didn't seem to work on the MiSTer. not sure what i'm missing

**Comment by paulb-nl** [comment]
I have the same results. They don't work at all on Mister after changing them to mapper 48. Even with the header set to mapper 33 Mesen will use 48 because it has an internal database.

**Comment by greyrogue** [comment]
Looks like I may have messed up the IRQ address order (C002/3 swapped).  I missed the subtle order in the table at the bottom of the Mapper 48 nesdev page.  Thanks for testing again. I must not have tested any of the mapper 48 games with IRQs.

**Comment by MP2E** [comment]
Just tried it out, works great! Thanks!
