### ISSUE TITLE
Rolling Thunder (USA) (Unl)

### ISSUE THREAD

**Issue by Hewhoisred** [MiSTer-devel/NES_MiSTer#79]
For reference, I'm aware that this is probably just an unsupported mapper.

Game displays heavily corrupted tiles almost immediately, first on the title screen, then in-game.  There is supposed to be text at the bottom of the play field and the colors also look wrong (blue door, for example).

Linked Youtube LP for reference:
https://www.youtube.com/watch?v=_LwUwrWfY1s

See attached screen shots.
![20190611_183504-Rolling Thunder (USA) (Unl)](https://user-images.githubusercontent.com/47957258/59317499-09ce7400-8c78-11e9-9fa3-dc4ad3b1658b.png)
![20190611_183512-Rolling Thunder (USA) (Unl)](https://user-images.githubusercontent.com/47957258/59317510-13f07280-8c78-11e9-86e1-8584f5efea9f.png)
![20190611_183738-Rolling Thunder (USA) (Unl)](https://user-images.githubusercontent.com/47957258/59317511-13f07280-8c78-11e9-9f90-7851bece6c7a.png)

**Comment by suverman** [comment]
Looks like Mapper 64 same as the Hard Drivin' Unl rom, the mapper list says it is supported.

**Comment by Kitrinx** [comment]
This should be resolved.

**Comment by Hewhoisred** [comment]
Confirmed fixed.  Closing.
