### ISSUE TITLE
Gall Force FDS - Pauses over and over again

### ISSUE THREAD

**Issue by funkycochise** [MiSTer-devel/NES_MiSTer#81]
The game pauses itself. If you press start to unpause, it pauses itself again.
The game is therefore unplayable.

**Comment by greyrogue** [comment]
Looks like this game actually pauses if disk eject is indicated.  The auto disk swapping code causes this to toggle continuously (the manual/button mode doesn't disable this either).

**Comment by Kitrinx** [comment]
This is now resolved by requiring manual mode FDS swapping.

**Comment by James-F2** [comment]
@funkycochise 
The issue has been solved please use the "close issue" button.
