### ISSUE TITLE
Randomly changing hsync position

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/NES_MiSTer#90]
When I cycle through NTSC, PAL, Dendy, I can see that it randomly change horizontal position sometimes on a CRT.
Cycling through them again may or may not fix pal horizontal position.

Can it be related to the PLL clock done recently?
This does not happen on the snes core with the new pal pll code, only on the nes core.
This is not my TV, since it doesn't happen with other cores, only the nes core.

@Kitrinx 
Sometimes in NTSC mode, it cuts the left column of pixels in the Grid test pattern in 240pee, on HDMI too!
Happens after cycling through the regions (System Type).
edit: 
Happens on the NES_PAL test build on Discord **before** the PLL changes.
So it is something related to changing regions.

**Comment by Kitrinx** [comment]
the reset signal when the region changes should probably be in top level to make it realign

**Comment by Kitrinx** [comment]
This should now be resolved, please let me know if it is not.

**Comment by James-F2** [comment]
Solved.
