### ISSUE TITLE
Bomberman - brown bricks

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/NES_MiSTer#92]
> I am getting this too when scrolling to the right but it also happens with builds before this change. It seems it is caused by something after June 15th because with that build it doesn't happen.
>
> Also those blocks are all background tiles. The only sprites are Bomberman and the enemies.

![60110760-48365980-9775-11e9-852c-b864061836b1](https://user-images.githubusercontent.com/31185814/60113759-1aecaa00-977b-11e9-97c3-13edac1cd366.jpg)

**Comment by James-F2** [comment]
@paulb-nl 
Quite possible this:
https://github.com/MiSTer-devel/NES_MiSTer/commit/d64ccbcfd565fe6a1652a2f6badf8341ada806df

**Comment by MP2E** [comment]
I see this issue on a build I made 2 days ago, June 23rd, as well

**Comment by James-F2** [comment]
June 21 fine,, 23 not fine.

It narrows down to:
1. gated clock for clk_sys.
2. SDRAM changes.

**Comment by paulb-nl** [comment]
I tried a few different Fitter seed values but same results.

**Comment by sorgelig** [comment]
I think i've fixed it in latest commit.

**Comment by James-F2** [comment]
Yep, it's fixed.
I'm closing this.
